"""vumanchu — the VuManChu WaveTrend / Money-Flow / VWAP maths, Python side.

ONE Python copy, golden-tested bit-for-bit against `js/vumanchuCore.js` via
`vumanchu_vectors.json` (generated by `scripts/gen_vumanchu_vectors.mjs`).
Retires nothing yet, but it is the brick the three drifting copies
(`Gold/modules/vumanchu.py`, `GoldV2/modules/vumanchu.py`,
`ConfluenceBot/modules/vumanchu.py`) should collapse into — see
`LEGO_MODULES.md §2` row "VuManChu WT/MF/VWAP".

────────────────────────────────────────────────────────────────────────────
TWO FAMILIES OF FUNCTION, AND THE DIFFERENCE MATTERS
────────────────────────────────────────────────────────────────────────────
`parity_*`  — bit-identical ports of the JS brick. Use when you must reproduce
              what the live chart / Telegram pane drew. `parity_money_flow`
              and `parity_vwap_osc` normalise by the max over the WHOLE array,
              which is fine live (the array ends at "now") and is LOOK-AHEAD
              the moment you feed them history and read a mid-array value.

`causal_*`  — the research variants. Same shape, no future in them. These are
              what a feature panel or an ML training matrix must use.

The distinction is deliberate and load-bearing: a silent "fix" to the parity
functions would move every number the live pane draws. Nothing here mutates
the JS brick's behaviour.

────────────────────────────────────────────────────────────────────────────
WHAT IS AND IS NOT CAUSAL IN THE ORIGINAL
────────────────────────────────────────────────────────────────────────────
  WT1 / WT2      pure EMA/SMA chains — already causal, parity == causal.
  Money Flow     normalised by max|raw| over the whole array  → NOT causal.
  VWAP osc       (a) anchored at bar 0 of whatever window you passed, so it
                 ramps one way and stops oscillating once price trends
                 (measured: 99.3% cross-timeframe agreement, i.e. no
                 timeframe-specific information — LEGO_MODULES.md §mtfStack);
                 (b) also max-normalised → NOT causal.
                 `causal_vwap_dist` replaces BOTH problems with a rolling
                 window VWAP expressed in σ units.

────────────────────────────────────────────────────────────────────────────
MONEY FLOW ON FX — READ THIS BEFORE INTERPRETING IT
────────────────────────────────────────────────────────────────────────────
OANDA's `volume` is a TICK COUNT, not size traded. So MF is activity-weighted
candle direction, not money changing hands. It is still the only leg of the
three carrying information that is not a pure transform of price, which is
exactly why it is worth measuring — but its asset-class comparison is partly a
comparison of feed artifacts. State that wherever its numbers are reported.

Amplitude is also unreliable raw: real M15 has ~18x volume outliers that
squash the series flat when you divide by the single largest bar (which is why
`js/vumanchuChart.js` draws it on a robust percentile). `causal_money_flow`
uses a ROLLING robust percentile — same intent, no future.

Vectorised via pandas `ewm(adjust=False)`, which is exactly the JS recurrence
`out[i] = v[i]*k + out[i-1]*(1-k)` seeded at `out[0] = v[0]`, so the speed
costs no fidelity (proven in `vumanchu_test.py`).
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

# Divide-by-zero guard on the WaveTrend channel index. Must equal
# `js/vumanchuCore.js` WT_EPS — the whole point of the golden test.
WT_EPS = 1e-10

# The operator's TradingView Cipher B setup (matches js/vumanchuChart.js
# defaults, which were validated against his Pine f_findDivs).
OPERATOR_WT = dict(n1=9, n2=12, sp=3)
# The vumanchuCore library defaults — different, and NOT interchangeable.
LIBRARY_WT = dict(n1=10, n2=21, sp=4)


# ── primitives (bit-identical to the JS ema/sma) ─────────────────────────────

def ema(values, period: int) -> np.ndarray:
    """EMA seeded at the first value — `out[0] = v[0]`, k = 2/(period+1)."""
    v = np.asarray(values, dtype=float)
    if v.size == 0 or period <= 0:
        return np.empty(0)
    k = 2.0 / (period + 1)
    return pd.Series(v).ewm(alpha=k, adjust=False).mean().to_numpy()


def sma(values, period: int) -> np.ndarray:
    """Simple MA; NaN for the first `period-1` slots, as the JS does."""
    v = np.asarray(values, dtype=float)
    if v.size == 0:
        return np.empty(0)
    return pd.Series(v).rolling(period).mean().to_numpy()


# ── WaveTrend ────────────────────────────────────────────────────────────────

@dataclass
class WaveTrend:
    wt1: np.ndarray
    wt2: np.ndarray


def wave_trend(high, low, close, n1: int = 10, n2: int = 21, sp: int = 4) -> WaveTrend:
    """hlc3 -> esa=EMA(n1) -> d=EMA(|hlc3-esa|,n1) -> ci=(hlc3-esa)/(0.015*d)
    -> wt1=EMA(ci,n2) -> wt2=SMA(wt1,sp).

    Causal by construction. Self-normalising (divides by an EMA of its own mean
    absolute deviation), so a 5m WT and a 30m WT live in the same ~±100 range
    and are directly comparable without rescaling.
    """
    h = np.asarray(high, dtype=float)
    l = np.asarray(low, dtype=float)
    c = np.asarray(close, dtype=float)
    hlc3 = (h + l + c) / 3.0
    esa = ema(hlc3, n1)
    d = ema(np.abs(hlc3 - esa), n1)
    ci = np.where(d > WT_EPS, (hlc3 - esa) / (0.015 * np.where(d > WT_EPS, d, 1.0)), 0.0)
    wt1 = ema(ci, n2)
    return WaveTrend(wt1=wt1, wt2=sma(wt1, sp))


# ── Money Flow ───────────────────────────────────────────────────────────────

def money_flow_raw(open_, high, low, close, volume=None) -> np.ndarray:
    """Per-bar directional volume pressure, UNNORMALISED and UNSMOOTHED:
    `(close-open)/(high-low) * volume`.

    Normalisation and smoothing are deliberately the caller's choice — that is
    the step where the look-ahead lives, so it is not buried in here.
    `volume=None` reproduces the JS `?? 1` fallback (unweighted candle
    direction), which is what happens on any feed without a volume column.
    """
    o = np.asarray(open_, dtype=float)
    h = np.asarray(high, dtype=float)
    l = np.asarray(low, dtype=float)
    c = np.asarray(close, dtype=float)
    rng = h - l
    rng = np.where(rng != 0, rng, 1e-10)
    vol = np.ones_like(c) if volume is None else np.asarray(volume, dtype=float)
    return (c - o) / rng * vol


def parity_money_flow(open_, high, low, close, volume=None, period: int = 14) -> np.ndarray:
    """LOOK-AHEAD. Bit-identical to `vumanchuCore.computeMoneyFlow`: divides by
    max|raw| over the whole array, THEN smooths.

    Correct for a live read (array ends now); wrong for a historical panel,
    where bar i's value would depend on a spike thousands of bars later. Sign
    and rank survive that; every absolute threshold (`mf > 20`, OB/OS bands)
    does not. Use `causal_money_flow` for research.

    The contamination is SILENT, not loud, and the test pins this: because the
    divisor is the max over the whole array, a truncated run is bit-identical
    to the full one whenever the cut falls AFTER the global peak, and only
    differs when it falls before. So a spot-check on one window can show a
    clean zero difference and wrongly certify this as causal.
    """
    raw = money_flow_raw(open_, high, low, close, volume)
    if raw.size == 0:
        return raw
    peak = np.max(np.abs(raw))
    if not np.isfinite(peak) or peak == 0:
        peak = 1.0
    return ema(raw / peak * 100.0, period)


def causal_money_flow(open_, high, low, close, volume=None, period: int = 14,
                      window: int = 2000, pctile: float = 99.0,
                      min_periods: int = 200, clamp: float = 150.0) -> np.ndarray:
    """Causal Money Flow: smooth first, then scale by a TRAILING robust spread.

    Scale at bar i is the `pctile`-th percentile of |raw| over the preceding
    `window` bars (inclusive of i, which is knowable at i). Robust rather than
    a max because real M15 volume carries ~18x outliers that flatten the series
    when you divide by the single largest bar — the same reason the chart
    renderer draws it on a percentile. Clamped on amplitude only, never on
    sign, so an excursion cannot dominate a feature column.

    Leading bars (< `min_periods` of history) are NaN rather than guessed — a
    panel must be able to drop its own warm-up.
    """
    raw = money_flow_raw(open_, high, low, close, volume)
    if raw.size == 0:
        return raw
    smoothed = ema(raw, period)
    scale = (pd.Series(np.abs(raw))
             .rolling(window, min_periods=min_periods)
             .quantile(pctile / 100.0)
             .to_numpy())
    with np.errstate(divide='ignore', invalid='ignore'):
        out = np.where((scale > 0) & np.isfinite(scale), smoothed / scale * 100.0, np.nan)
    return np.clip(out, -clamp, clamp)


# ── VWAP ─────────────────────────────────────────────────────────────────────

def parity_vwap_osc(high, low, close, volume=None) -> tuple[np.ndarray, np.ndarray]:
    """LOOK-AHEAD *and* DEGENERATE. Bit-identical to `vumanchuCore.computeVWAP`
    — VWAP anchored at bar 0 of whatever array you passed, oscillator =
    (close - vwap) max-normalised.

    Kept only for parity with what the live pane can draw. Two independent
    problems, both measured (LEGO_MODULES.md §mtfStack): the bar-0 anchor makes
    it ramp one way and pin at its own normalisation peak once price trends
    (35 -> 100 on a trending fixture, yielding ZERO divergences), and it agrees
    99.3% across timeframes, i.e. it carries no timeframe-specific information
    at all. Do not build a multi-timeframe feature on this. Returns
    `(vwap, osc)`.
    """
    h = np.asarray(high, dtype=float)
    l = np.asarray(low, dtype=float)
    c = np.asarray(close, dtype=float)
    tp = (h + l + c) / 3.0
    vol = np.ones_like(c) if volume is None else np.asarray(volume, dtype=float)
    cum_vol = np.cumsum(vol)
    cum_tpv = np.cumsum(tp * vol)
    vwap = np.where(cum_vol > 0, cum_tpv / np.where(cum_vol > 0, cum_vol, 1.0), tp)
    raw = c - vwap
    peak = np.max(np.abs(raw)) if raw.size else 1.0
    if not np.isfinite(peak) or peak == 0:
        peak = 1.0
    return vwap, raw / peak * 100.0


def rolling_vwap(high, low, close, volume=None, window: int = 20,
                 min_periods: int | None = None) -> np.ndarray:
    """Rolling-window VWAP — the variant that stays an oscillator.

    The window scales with the timeframe (20 M1 bars vs 20 M15 bars cover
    different spans), which is precisely why this one carries timeframe-
    specific information where the cumulative anchor does not (measured 76.7%
    cross-timeframe agreement vs 99.3%).
    """
    h = np.asarray(high, dtype=float)
    l = np.asarray(low, dtype=float)
    c = np.asarray(close, dtype=float)
    tp = (h + l + c) / 3.0
    vol = np.ones_like(c) if volume is None else np.asarray(volume, dtype=float)
    mp = window if min_periods is None else min_periods
    num = pd.Series(tp * vol).rolling(window, min_periods=mp).sum().to_numpy()
    den = pd.Series(vol).rolling(window, min_periods=mp).sum().to_numpy()
    with np.errstate(divide='ignore', invalid='ignore'):
        return np.where(den > 0, num / den, np.nan)


def causal_vwap_dist(high, low, close, volume=None, window: int = 20,
                     sigma_window: int = 500, min_periods: int = 100) -> np.ndarray:
    """Price distance from the rolling VWAP, in units of trailing return σ.

    σ-normalising is what makes the column comparable across instruments and
    across volatility regimes — a 3-pip stretch on EURCHF and a $4 stretch on
    gold become the same number. Fully causal: both the VWAP window and the σ
    window look only backwards.
    """
    c = np.asarray(close, dtype=float)
    vw = rolling_vwap(high, low, close, volume, window=window)
    ret = pd.Series(c).pct_change()
    sig = ret.rolling(sigma_window, min_periods=min_periods).std().to_numpy() * c
    with np.errstate(divide='ignore', invalid='ignore'):
        return np.where((sig > 0) & np.isfinite(sig), (c - vw) / sig, np.nan)


# ── causal multi-timeframe alignment ─────────────────────────────────────────

def align_htf_causal(fast_close_sec, slow_close_sec, slow_series) -> np.ndarray:
    """Step-hold a slow-timeframe series onto the fast grid, CAUSALLY.

    Port of `js/vumanchuMtf.js alignHtfCausal`. For each fast bar, takes the
    last slow bar whose CLOSE is at or before that fast bar's close — so every
    value was genuinely knowable at that position.

    This is THE multi-timeframe correctness trap: forward-filling a 15m
    oscillator onto 1m rows by start-time leaks up to 14 minutes of future into
    every single row, and an MTF agreement study built on that leak looks
    spectacular for entirely mechanical reasons. The causal version sits up to
    one slow bar further right and looks "late" — that lateness is real
    information, not an artefact to tune away.

    Both arguments are bar CLOSE times in epoch seconds. Returns an array
    aligned to the fast grid, NaN before the first slow bar has closed.
    """
    f = np.asarray(fast_close_sec, dtype=float)
    s = np.asarray(slow_close_sec, dtype=float)
    vals = np.asarray(slow_series, dtype=float)
    if f.size == 0 or s.size == 0:
        return np.full(f.size, np.nan)
    # Index of the last slow bar closed at or before each fast close.
    k = np.searchsorted(s, f, side='right') - 1
    out = np.full(f.size, np.nan)
    ok = k >= 0
    out[ok] = vals[k[ok]]
    return out


# ── agreement between two timeframes ─────────────────────────────────────────

AGREE_MODES = ('direction', 'level', 'zone')


def agreement(fast_wt1, fast_wt2, slow_wt1, slow_wt2, mode: str = 'level',
              ob: float = 53.0, os_: float = -53.0) -> np.ndarray:
    """Per-bar agreement between two timeframes of the SAME oscillator.

    Returns +1 agree / 0 disagree / NaN not-comparable, so the caller can count
    `comparable` honestly rather than treating NaN as disagreement.

      direction — both waves rolling the same way (sign of wt1-wt2)
      level     — both the same side of zero          (the DEFAULT)
      zone      — both overbought, or both oversold   (NaN otherwise)

    WHY `direction` IS NOT THE DEFAULT, measured on fixtures
    (`js/vumanchuMtf.js` header): the slow wave's slope is a heavily smoothed,
    delayed version of the fast one's, so when the price's dominant cycle is
    short relative to that lag the two sit OUT OF PHASE and `direction` reports
    systematic disagreement far BELOW its own chance baseline — 15.8% vs ~51%
    at cycle/lag = 1.0, rising monotonically and only crossing the baseline
    near cycle/lag ~= 7. For WT 9/12/3 read at 1m vs 15m the lag is roughly
    n2 x ratio = 180 M1 bars ~= 3 hours, so most intraday cycles land in the
    anti-agreement zone. A low `direction` number is differential smoothing
    lag, NOT the timeframes fighting.

    On a broadband fixture the three modes split hard vs their baselines:
    direction -23.8pp, level +5.1pp, zone +15.2pp.

    NEVER read the resulting agreement rate on its own — two timeframes of one
    oscillator on one price series are correlated BY CONSTRUCTION (the slow is
    close to a smoothed fast). Pair it with `rephasing_baseline`.
    """
    f1 = np.asarray(fast_wt1, dtype=float)
    f2 = np.asarray(fast_wt2, dtype=float)
    s1 = np.asarray(slow_wt1, dtype=float)
    s2 = np.asarray(slow_wt2, dtype=float)
    valid = np.isfinite(f1) & np.isfinite(s1)
    out = np.full(f1.shape, np.nan)

    if mode == 'direction':
        valid &= np.isfinite(f2) & np.isfinite(s2)
        out[valid] = (np.sign(f1 - f2)[valid] == np.sign(s1 - s2)[valid]).astype(float)
    elif mode == 'level':
        out[valid] = (np.sign(f1)[valid] == np.sign(s1)[valid]).astype(float)
    elif mode == 'zone':
        fz = np.where(f1 >= ob, 1.0, np.where(f1 <= os_, -1.0, np.nan))
        sz = np.where(s1 >= ob, 1.0, np.where(s1 <= os_, -1.0, np.nan))
        comparable = valid & np.isfinite(fz) & np.isfinite(sz)
        out[comparable] = (fz[comparable] == sz[comparable]).astype(float)
    else:
        raise ValueError(f'agreement: unknown mode {mode!r} (want one of {AGREE_MODES})')
    return out


def rephasing_baseline(fast_wt1, fast_wt2, slow_wt1, slow_wt2, mode: str = 'level',
                       shifts: int = 24, ob: float = 53.0, os_: float = -53.0) -> float:
    """The chance baseline for `agreement`, by deterministic circular re-phasing.

    Rolls the slow series through `shifts` evenly-spaced circular offsets and
    averages the agreement rate. That preserves BOTH series' own persistence
    and marginal distribution while destroying their true time correspondence
    — so it answers "how much of this agreement is mechanical?".

    Read `delta = agree_rate - baseline`, never the raw rate. A structural
    baseline, not a significance test.
    """
    n = len(np.asarray(fast_wt1))
    if n == 0 or shifts < 1:
        return float('nan')
    s1 = np.asarray(slow_wt1, dtype=float)
    s2 = np.asarray(slow_wt2, dtype=float)
    rates = []
    for j in range(1, shifts + 1):
        off = (j * n) // (shifts + 1)
        if off == 0:
            continue
        a = agreement(fast_wt1, fast_wt2, np.roll(s1, off), np.roll(s2, off),
                      mode=mode, ob=ob, os_=os_)
        finite = a[np.isfinite(a)]
        if finite.size:
            rates.append(float(finite.mean()))
    return float(np.mean(rates)) if rates else float('nan')
