// js/dataFeeds.js — every data FEED the desk runs on: what it is, what it is for, how it
// refreshes and where it lands. The registry behind the 🗄 Data Map (js/dataMap.js).
//
// FEED, NOT SERIES. js/dataCatalogue.js is the series catalogue -- one row per FRED/CBOE/
// CME id with why / verdict / trap. This file is one level up: the pipelines those
// series travel through (a fetch, a cache, a refresh cycle, the endpoints that serve
// it). A feed names the catalogue rows it carries with `series: [readBy keys]`, so the
// map shows each feed's series and their traps without a second copy of either.
//
// WHAT IS NOT HERE ON PURPOSE. "Which pages use this feed" is not written down: the
// server scans every page and js/ module for each feed's `endpoints` (js/dataCatalogueCore
// scanUsage), because the API Map's hand-kept consumers column has already drifted.
// `consumers` below is only for readers a scan cannot see -- Python bots, cron workers,
// the morning brief's server-side assembly.
//
// THE GUARD. Every external host the server fetches must be claimed by a feed's `hosts`
// or listed in IGNORE_HOSTS; anything else shows as a warning on the map and fails
// js/dataCatalogue.test.mjs. Add a feed to server.js without describing it here and you
// will hear about it.
//
// Fields:
//   id, name, provider, category   identity
//   purpose     one line: what the desk uses it for (the question it answers)
//   details     what is actually pulled
//   refresh     how and when it refreshes -- including whether a deploy empties it
//   store       where it lives (memory var, KV key, R2 prefix, file)
//   endpoints   /api routes that serve it (scanned for consumers)
//   health      ids of rows in /api/data-health that time it ('x:*' = prefix)
//   kvStamp     {key, cadenceDays, market} -- a KV value the server reads a timestamp from
//   series      readBy keys into js/dataCatalogue.js
//   hosts       external hosts this feed fetches from
//   kind        'file' for a committed file / offline export (no schedule to check)
//
// Pure data. No fetch, no DOM.

export const FEED_CATEGORIES = [
  { id: 'prices',      label: 'Market prices',          colour: '#10b981', blurb: 'the tape everything else is measured against' },
  { id: 'rates',       label: 'Rates & liquidity',      colour: '#38bdf8', blurb: 'curves, real yields, funding plumbing' },
  { id: 'macro',       label: 'Macro & releases',       colour: '#34d399', blurb: 'what printed, what was expected, what is next' },
  { id: 'vol',         label: 'Volatility & options',   colour: '#a78bfa', blurb: 'implied and realised vol, the option book' },
  { id: 'positioning', label: 'Positioning & sentiment', colour: '#f59e0b', blurb: 'who is long, what central banks said' },
  { id: 'crossasset',  label: 'Cross-asset',            colour: '#f472b6', blurb: 'equities, credit, commodities, correlations' },
  { id: 'desk',        label: 'Desk outputs',           colour: '#94a3b8', blurb: 'the desk’s own written reads and bot logs' },
  { id: 'files',       label: 'Files & research pulls', colour: '#64748b', blurb: 'static exports, backfills, on-demand research fetches' },
];

/** Hosts the server talks to that are not data feeds. */
export const IGNORE_HOSTS = [
  'anthropic.com',            // LLM calls
  'telegram.org',             // alerts out
  'r2.cloudflarestorage.com', 'r2.dev', 'cloudflare.com',   // our own storage / KV
  'github.com', 'githubusercontent.com', 'tradingview.com', 'sheetjs.com', 'cdnjs.cloudflare.com', 'jsdelivr.net',
  'localhost', '127.0.0.1', 'example.com', 'railway.app', 'macrofxmodel.com', 'claude.ai', 'w3.org',
  'cftc.gov',                 // links to the COT archive in help text (the API host is claimed below)
  'drive.usercontent.google.com', 'google.com', 'googleapis.com',   // one-off M1 archive download in a backtest engine
];

export const FEEDS = [
  // ── Market prices ────────────────────────────────────────────────────────
  { id: 'oanda_candles', name: 'OANDA candles & quotes', provider: 'OANDA v3', category: 'prices',
    purpose: 'The price tape: every forecast band, range-used gauge, level and backtest is computed on these bars.',
    details: 'M1/M5/H1/D1 candles for the 26 FX pairs, gold, indices and copper; live pricing for quotes and spreads.',
    refresh: 'On demand plus the vol-forecast scheduler (daily London run, rebuilt on boot). Live quotes stream through the worker.',
    store: 'forecastState.ohlcCache (memory) · _m5SrvCache · atlas caches',
    endpoints: ['/api/ohlc', '/api/quote', '/api/oanda_ohlc5m', '/api/oanda_stream', '/api/oanda-instruments', '/api/vol-forecast'],
    health: ['oanda'], hosts: ['oanda.com'],
    consumers: 'every Python bot via /api/quote; cron-worker proximity alerts (direct OANDA pricing)' },
  { id: 'oanda_spreads', name: 'Live spreads & spread profile', provider: 'OANDA v3', category: 'prices',
    purpose: 'Execution cost: the “spread elevated, consider waiting” warning and the cost line in every backtest.',
    details: 'Account pricing endpoint sampled for bid/ask; a 10-minute profile builds the typical spread by hour.',
    refresh: '20-second cache on request; profile every 10 min (first run 60 s after boot).',
    store: '_spreadsCache (memory) · KV spread profile',
    endpoints: ['/api/spreads', '/api/spread-profile'], health: ['spreads'] },
  { id: 'oanda_books', name: 'OANDA order & position books', provider: 'OANDA v3', category: 'positioning',
    purpose: 'Retail positioning and resting-order clusters per pair — a crowding read, not a signal on its own.',
    details: 'positionBook / orderBook snapshots per instrument.',
    refresh: 'Every 10 min (first run 4 min after boot). KV persists across deploys.',
    store: 'KV oanda_book_history_v1', endpoints: ['/api/oanda-book/history', '/api/oanda_book'],
    kvStamp: { key: 'oanda_book_history_v1', cadenceDays: 1 } },
  { id: 'oanda_financing', name: 'Financing (swap) rates', provider: 'OANDA v3', category: 'prices',
    purpose: 'The carry actually paid or earned holding a position overnight — feeds the carry read and cost models.',
    details: 'Per-instrument long/short financing rates from the account instruments endpoint.',
    refresh: 'Daily interval; manual capture via POST /api/financing/capture-now.',
    store: 'KV oanda_financing_history', endpoints: ['/api/financing/history', '/api/financing/capture-now'],
    kvStamp: { key: 'oanda_financing_history', cadenceDays: 1 } },
  { id: 'futures_quote', name: 'Futures & index quotes', provider: 'Yahoo Finance', category: 'prices',
    purpose: 'Live CME futures prices (6E, 6B, 6J, GC, NQ, ES…) and DAX/FTSE where OANDA has no equivalent.',
    details: '1-minute chart quotes from query1/query2, falling back to OANDA.',
    refresh: 'On request, no cache.', store: 'none (pass-through)',
    endpoints: ['/api/futures-quote'], hosts: ['finance.yahoo.com'] },
  { id: 'm1_archive', name: 'M1 bar archive', provider: 'Cloudflare R2', category: 'prices',
    purpose: 'Years of one-minute bars per pair — the history every honest backtest and the Level Atlas replay on.',
    details: 'Parquet per pair under analogml/m1 and m1/; public bid CSVs per timeframe for the browser backtests.',
    refresh: 'AnalogML refresh_m1.py pulls new OANDA M1 hourly and mirrors to R2; older history is a one-off backfill.',
    store: 'R2 m1/, analogml/m1/{pair}_m1.parquet, public r2.dev CSVs',
    endpoints: ['/api/level-atlas/m1-tail'],
    files: ['analysis.html', 'backtest.html', 'claude-backtest.html', 'gold-backtest.html', 'gold-lab.html'],
    consumers: 'AnalogML motif bot; local decision engines (sync.mjs)' },

  // ── Rates & liquidity ────────────────────────────────────────────────────
  { id: 'fred_dash', name: 'FRED dashboard snapshot', provider: 'FRED', category: 'rates',
    purpose: 'The macro snapshot behind the main dashboard tiles and the Python bots’ VIX gate.',
    details: 'Latest + previous value for ~30 series: the curve, real yields, breakevens, dollar, HY OAS, foreign 10y and short rates, WTI, the liquidity legs; copper from OANDA.',
    refresh: 'On boot, then every 6h (skipped if KV is under 5h old; retries at +2 and +4 min). KV persists.',
    store: 'KV fred_data_v3 (mirrored to fred for the bots)', endpoints: ['/api/fred'],
    health: ['fredDash'], series: ['fredDash'], hosts: ['stlouisfed.org'],
    consumers: 'Python bots’ vol_gate (KV fred)' },
  { id: 'fred_history', name: 'FRED history (90 obs)', provider: 'FRED', category: 'rates',
    purpose: '1-day / 5-day / 20-day changes for the chain read, the compass and the macro-change tiles.',
    details: '90 observations each of the curve, real yields, VIX/VIX3M, HY OAS, yen, SOFR, RRP, IORB, term premium and the OECD foreign rates.',
    refresh: '30 s after boot (skips keys already present), then every 6h. KV persists, 24h TTL.',
    store: 'KV fredhistory_series_<key>', endpoints: ['/api/fredhistory', '/api/macro-changes'] },
  { id: 'rates', name: 'Rates & policy complex', provider: 'FRED + NY Fed', category: 'rates',
    purpose: 'The curve, real yields, term premium and the funding plumbing (SOFR, EFFR, IORB, SRF, RRP, discount window).',
    details: 'Keyless fredgraph CSVs plus the NY Fed SOFR 99th percentile.',
    refresh: 'Every 6h, plus a boot run 7 min after a deploy; also refreshed on request when older than 6h. In memory, so a deploy empties it until then.',
    store: '_rates (memory)', endpoints: ['/api/rates'], health: ['rates'], series: ['rates'], hosts: ['newyorkfed.org'] },
  { id: 'chapters', name: 'Curve & inflation chapters', provider: 'FRED', category: 'rates',
    purpose: 'The full Treasury curve, TIPS, breakevens, CPI/PCE/PPI and wages for the chapter pages.',
    details: '21 keyless CSV series plus legs borrowed from the drill bundle.',
    refresh: 'Boot run 12 min after a deploy, then on request when older than 12h. In memory.',
    store: '_chapters (memory)', endpoints: ['/api/chapters'], health: ['chapters'], series: ['chapters'] },
  { id: 'intl_yields', name: 'International yields', provider: 'BoE · Bundesbank · Japan MoF', category: 'rates',
    purpose: 'Gilt, bund and JGB yields at daily frequency — the chain’s gap chips (gilt/bund/JGB minus Treasuries).',
    details: 'BoE IADB gilt series, Bundesbank 10y, MoF JGB CSVs.',
    refresh: 'Every 6h; on request when older than 6h. In memory.',
    store: '_intlYields (memory)', endpoints: ['/api/intl-yields'], health: ['intlYields'],
    hosts: ['bankofengland.co.uk', 'bundesbank.de', 'mof.go.jp'] },
  { id: 'ecb_sdw', name: 'ECB yield curve & €STR', provider: 'ECB Data Portal', category: 'rates',
    purpose: 'Euro-area 2y/10y AAA curve and €STR for the EUR legs of the yield-coupling and rate reads.',
    details: 'SR_2Y / SR_10Y from the AAA curve; €STR and DE10Y via the worker.',
    refresh: 'On request (6h cache); worker caches daily in KV.', store: '_ycRealCache · KV ecbsdw_daily',
    endpoints: ['/api/ecbsdw', '/api/yield-coupling-real'], hosts: ['ecb.europa.eu'] },
  { id: 'treasury_tga', name: 'Treasury cash balance (TGA)', provider: 'US Treasury Fiscal Data', category: 'rates',
    purpose: 'Daily TGA — the liquidity drain the weekly Fed series only show with a lag.',
    details: 'Daily Treasury Statement operating cash balance.',
    refresh: 'On request (liquidity pulse) and the weekday COG shadow cron.', store: 'LIQ_PULSE_CACHE (memory)',
    endpoints: ['/api/liquidity-pulse/data'], hosts: ['fiscaldata.treasury.gov'] },
  { id: 'weekmap', name: 'The week, scored', provider: 'FRED + OANDA + NY Fed', category: 'rates',
    purpose: 'Every macro series’ weekly move z-scored against its own history, with analogue weeks.',
    details: '25 FRED series (policy, funding, liquidity, credit, vol) plus gold, copper, SPX, EUR/USD.',
    refresh: '14 min after boot, then every 24h; on request when stale. In memory.',
    store: '_weekMap (memory)', endpoints: ['/api/weekmap'], health: ['weekmap'], series: ['weekMap'] },

  // ── Macro & releases ─────────────────────────────────────────────────────
  { id: 'econ_engines', name: 'Currency fundamentals (econ engines)', provider: 'FRED + national stats', category: 'macro',
    purpose: 'Per-currency labour, CPI, GDP, ISM, retail sales, trade, real yields, rate differentials, PPI, curve, confidence — the macro scorecard.',
    details: '12 engines (js/*Engine.js), each with its own series set per currency.',
    refresh: 'Release poller every 10 min; each engine only refetches when its latest print is older than its due window (35 days monthly, 100 GDP). KV persists.',
    store: 'KV labor_market_v1, cpi_v1, gdp_v1, ism_v1, retail_sales_v1, trade_balance_v1, real_yield_v1, rate_diff_v1, ppi_v1, yield_curve_v1, consumer_confidence_v1, credit_quality_v1',
    endpoints: ['/api/labor-market', '/api/cpi', '/api/gdp', '/api/ism', '/api/retail-sales', '/api/trade-balance', '/api/real-yield', '/api/rate-diff', '/api/ppi', '/api/yield-curve', '/api/consumer-confidence', '/api/credit-quality', '/api/macro-scorecard'],
    kvStamp: { key: 'cpi_v1', cadenceDays: 35, market: false } },
  { id: 'nowcast', name: 'Nowcasts (Cleveland Fed + GDPNow)', provider: 'Cleveland Fed · Atlanta Fed (via FRED)', category: 'macro',
    purpose: 'What CPI/PCE and GDP are tracking before they print — context for the release, not a lean.',
    details: 'Cleveland Fed nowcast_month.json (CPI, core, PCE, core PCE m/m) and the GDPNOW series.',
    refresh: '11 min after boot, then every 24h; on request when stale. In memory.',
    store: '_nowcast (memory)', endpoints: ['/api/nowcast'], health: ['nowcast'], series: ['nowcast'], hosts: ['clevelandfed.org'] },
  { id: 'macro_regime', name: 'Growth × inflation regime', provider: 'FRED · ONS · Eurostat · StatCan', category: 'macro',
    purpose: 'Which macro quadrant each currency sits in (USD, GBP, EUR, CAD) and what markets did there.',
    details: 'CFNAI, claims, industrial production, payrolls, core CPI/PCE, breakevens; ONS, Eurostat and StatCan equivalents.',
    refresh: '12 min after boot, then every 24h. In memory (history also on disk).',
    store: '_macroRegime (memory) · analysis/output/regime.json', endpoints: ['/api/regime'],
    health: ['regime'], series: ['regime'], hosts: ['ons.gov.uk', 'statcan.gc.ca', 'ec.europa.eu'] },
  { id: 'macro_regime_fx', name: 'Regime-conditioned FX study', provider: 'FRED', category: 'macro',
    purpose: 'How each pair behaves in each macro regime, and how many cuts/hikes are priced.',
    details: 'Real yields, HY OAS, the curve, fed funds and the H.10 FX fixings (keyed API).',
    refresh: '2 min after boot, then every 24h. KV persists.', store: 'KV macro_regime_fx_v1',
    endpoints: ['/api/macro-regime-fx'], kvStamp: { key: 'macro_regime_fx_v1', cadenceDays: 1, market: false } },
  { id: 'surprise_store', name: 'Release surprises (actual vs consensus)', provider: 'ForexFactory · FRED vintages · BoE/BoC/RBA', category: 'macro',
    purpose: 'Every release’s surprise, first print — the history behind news sizing and the event-response book.',
    details: '~26k rows: calendar consensus, first-print actuals from FRED realtime vintages, policy-rate actuals from the BoE, BoC and RBA.',
    refresh: 'Backfill + refresh at boot, then hourly. KV persists.', store: 'KV econ_surprise_v1',
    endpoints: ['/api/econ-surprise', '/api/surprise'], kvStamp: { key: 'econ_surprise_v1', cadenceDays: 1 },
    hosts: ['bankofcanada.ca', 'rba.gov.au'] },
  { id: 'ff_calendar', name: 'Economic calendar (this week)', provider: 'ForexFactory (Finnhub fallback)', category: 'macro',
    purpose: 'What prints when, and how big — the news gate the bots trade around and the brief’s event list.',
    details: 'ff_calendar_thisweek.json, 30-min module cache.',
    refresh: 'Event gate on boot then hourly; written to KV for the bots.', store: 'KV event_windows_v1',
    endpoints: ['/api/events', '/api/news-outcome', '/api/calendar-events'],
    kvStamp: { key: 'event_windows_v1', cadenceDays: 1, market: false }, hosts: ['faireconomy.media'],
    consumers: 'Python bots read KV event_windows_v1 to stand aside around releases' },
  { id: 'calendar_feed', name: 'Calendar with actuals', provider: 'ForexFactory + Nasdaq', category: 'macro',
    purpose: 'Events ahead plus actual vs consensus as they print, for the brief and the calendar page.',
    details: 'ForexFactory JSON for the week ahead; api.nasdaq.com economic events for actuals.',
    refresh: 'On request when older than 30 min. In memory only — nothing fills it until a page asks.',
    store: '_calFeed (memory)', endpoints: ['/api/calendar-feed'], health: ['calFeed'], hosts: ['nasdaq.com'] },
  { id: 'event_impact', name: 'Event vol impact', provider: 'Finnhub', category: 'macro',
    purpose: 'How much range each event type adds — scales the forecast bands on news days.',
    details: '18 months of Finnhub economic calendar (premium endpoint, often 403s) matched to realised ranges.',
    refresh: 'Boot auto-warm if missing or stale; manual refresh.', store: 'KV event_vol_impact',
    endpoints: ['/api/vol-forecast/event-impact'], kvStamp: { key: 'event_vol_impact', cadenceDays: 30, market: false }, hosts: ['finnhub.io'] },
  { id: 'gpr', name: 'Geopolitical risk index', provider: 'Caldara–Iacoviello GPR', category: 'macro',
    purpose: 'A daily geopolitical-risk read for the risk flags and macro context.',
    details: 'data_gpr_daily_recent.xls (needs the optional xlsx package).',
    refresh: 'Release poller, due after 8 days. KV persists.', store: 'KV gpr_v1',
    endpoints: ['/api/gpr'], kvStamp: { key: 'gpr_v1', cadenceDays: 8, market: false }, hosts: ['matteoiacoviello.com'] },

  // ── Volatility & options ─────────────────────────────────────────────────
  { id: 'cme_oi_iv', name: 'CME settles capture (OI + IV term structure)', provider: 'CME QuikStrike', category: 'vol',
    purpose: 'The live option book: open interest walls, max pain, dealer gamma and the per-expiry implied-vol curve for 41 instruments.',
    details: 'Nightly QuikStrike settles scraped by oi_recon/ and posted to KV; the server derives history, zones and calibrations from it.',
    refresh: 'Nightly capture outside the server (oi_recon/run_daily.py). Derived: OI history every 30 min, zones every 10 min.',
    store: 'KV oi_store (+ oi_store_py, oi_store_cmdty, oi_history, oi_bot_zones)',
    endpoints: ['/api/oi-today', '/api/oi-store', '/api/oi-levels', '/api/oi-history', '/api/oi-bot/zones', '/api/risk-flags'],
    health: ['oi_store'], series: ['oi', 'volIntelligence', 'ivLadderExport'], hosts: ['cmegroup.com'],
    consumers: 'oi_bot, range_line_bot (KV oi_bot_zones, range_line_oi); morning brief IV line' },
  { id: 'fred_iv', name: 'Implied vol indices (EVZ, GVZ)', provider: 'FRED (CBOE)', category: 'vol',
    purpose: 'EUR/USD and gold option-implied vol percentiles for the brief and risk flags.',
    details: 'EVZCLS and GVZCLS via the keyed API. EVZ stopped printing 2025-03-11 — the map shows it as dead on purpose.',
    refresh: 'On request (6h cache). No timer — /api/data-health and the brief trigger it.',
    store: 'CVOL_CACHE (memory)', endpoints: ['/api/cvol', '/api/risk-flags'],
    health: ['cvol:EVZCLS', 'cvol:GVZCLS'], series: ['cvol'] },
  { id: 'cme_cvol_file', name: 'CME CVOL export', provider: 'CME (manual export)', category: 'files', kind: 'file',
    purpose: 'ATM vol, skew and convexity for 7 FX/gold products since 2016 — research history for the vol-carry backtest.',
    details: 'js/data/cmeCvolEod.json, converted from an uploaded parquet by scripts/convertCmeCvol.py. CME’s endpoints 403, so it cannot be automated.',
    refresh: 'Manual — when someone re-exports it.', store: 'js/data/cmeCvolEod.json',
    endpoints: ['/api/cvol'], health: ['cvol:CME_*'], series: ['impliedVolCore', 'fxVolCarry'] },
  { id: 'cboe_file', name: 'CBOE vol index history', provider: 'CBOE (manual export)', category: 'files', kind: 'file',
    purpose: 'Long history of CBOE vol indices (VXN, GVZ…) for the implied-vol research engines.',
    details: 'js/data/cboeVolIndices.json, built by scripts/convertCboeVolContext.py from a CSV export.',
    refresh: 'Manual.', store: 'js/data/cboeVolIndices.json', consumers: 'js/impliedVolCore.js' },
  { id: 'vix_capture', name: 'VIX & VXN intraday capture', provider: 'Yahoo Finance', category: 'vol',
    purpose: 'One-minute VIX/VXN bars, kept because no free source keeps intraday vol-index history.',
    details: '^VIX and ^VXN 1-minute bars appended to R2.',
    refresh: '2 min after boot, then every 6h.', store: 'R2 vix_m1/', endpoints: ['/api/vix-capture'] },
  { id: 'vol_reference', name: 'Vol hit-rates & session stats', provider: 'Derived from OANDA', category: 'vol',
    purpose: 'How often each forecast line actually gets hit, per pair and session — the hit rates printed next to every level.',
    details: '90-day touch statistics per instrument and line; session range statistics.',
    refresh: 'Boot auto-warm plus the daily London cron. KV persists.', store: 'KV vol_hit_rates, session_stats',
    endpoints: ['/api/vol-forecast/hit-rates', '/api/session-stats'], kvStamp: { key: 'vol_hit_rates', cadenceDays: 1 } },

  // ── Positioning & sentiment ──────────────────────────────────────────────
  { id: 'cot', name: 'COT positioning', provider: 'CFTC (Socrata)', category: 'positioning',
    purpose: 'Weekly speculator positioning per currency and its extremes — the crowding read.',
    details: 'Legacy/TFF futures reports from publicreporting.cftc.gov; a 10-year factor history for the COT test.',
    refresh: 'Live routes recompute on request (worker KV cache). The factor history backfill is manual (POST /api/cot-backfill/run).',
    store: 'KV cot_extremes_v3, cot_series_v2, cot_factor_history_v1',
    endpoints: ['/api/cot', '/api/cot-extremes', '/api/cot-analysis', '/api/cot-backfill/status'],
    hosts: ['publicreporting.cftc.gov'] },
  { id: 'myfxbook', name: 'Retail sentiment', provider: 'Myfxbook community outlook', category: 'positioning',
    purpose: 'Percent of retail traders long/short per pair — a contrarian crowding read.',
    details: 'Community outlook via the worker.', refresh: 'On request with a KV TTL.', store: 'KV sentiment',
    endpoints: ['/api/sentiment'], hosts: ['myfxbook.com'] },
  { id: 'cb_text', name: 'Central-bank statements', provider: 'Fed · ECB · BoE · BoJ', category: 'positioning',
    purpose: 'Every statement, minutes and Beige Book, scored hawkish/dovish — the sentiment pages and the brief’s policy line.',
    details: 'Statement text fetched from each bank, scored with a lexicon and an LLM read.',
    refresh: 'Poll every 30 min (first poll 30 min after boot); manual fetch-now per bank. KV persists.',
    store: 'KV fomc_*, ecb_*, boe_*, boj_*, beigebook_*',
    endpoints: ['/api/fomc/latest', '/api/ecb/latest', '/api/boe/latest', '/api/boj/latest', '/api/beigebook/latest', '/api/fomc/history'],
    hosts: ['federalreserve.gov', 'boj.or.jp'] },
  { id: 'gold_etf', name: 'Gold ETF flows', provider: 'Yahoo Finance', category: 'positioning',
    purpose: 'GLD + IAU assets — whether the gold move is backed by money coming in.',
    details: 'quoteSummary total assets, one point appended per day.',
    refresh: 'On request only (6h cache): a day nobody opens the page is a day with no point recorded.',
    store: 'KV gold_etf_flow_history', endpoints: ['/api/gold-etf-flow'],
    kvStamp: { key: 'gold_etf_flow_history', cadenceDays: 1 } },
  { id: 'headlines', name: 'Market headlines', provider: 'Yahoo Finance RSS', category: 'positioning',
    purpose: 'Headlines for SPX, Nasdaq, gold, crude, the dollar and 10y — colour for the morning brief.',
    details: 'RSS per symbol, fetched while the brief is written.', refresh: 'On request, uncached.', store: 'none',
    endpoints: ['/api/morning-brief'] },

  // ── Cross-asset ──────────────────────────────────────────────────────────
  { id: 'drill', name: 'Drill bundle (71 series)', provider: 'FRED · CBOE · Yahoo · OANDA', category: 'crossasset',
    purpose: 'Six years of daily closes across rates, credit, vol, sectors and megacaps — the drill, the wider-market board and the scan.',
    details: '12 FRED series, 10 CBOE vol indices (VIX9D/3M/6M, VVIX, SKEW, VXN, RVX, DSPX, OVX, GVZ), 14 sector ETFs, 12 single names, OANDA legs.',
    refresh: 'Every 24h, plus a boot run 9 min after a deploy; on request when stale. In memory.',
    store: '_drillBundle (memory)', endpoints: ['/api/drill-series', '/api/drill-question', '/api/wider-market'],
    health: ['drill'], series: ['drill'], hosts: ['cboe.com'] },
  { id: 'crack', name: 'Crude & the crack spread', provider: 'FRED (EIA spot)', category: 'crossasset',
    purpose: 'WTI and the 3-2-1 crack — the oil → inflation channel on the chain and the crack card.',
    details: 'WTI, RBOB gasoline and heating oil spot (keyless CSV).',
    refresh: 'Every 6h, plus a boot run 8 min after a deploy; on request when older than 6h. In memory.',
    store: '_crack (memory)', endpoints: ['/api/crack'], health: ['crack'], series: ['crack'] },
  { id: 'corr', name: 'Correlations & betas', provider: 'Derived from OANDA', category: 'crossasset',
    purpose: 'Rolling correlations and betas between every instrument — hedge alerts and the concentration warning.',
    details: 'Correlation history and beta estimates computed from daily closes.',
    refresh: '60–90 s after boot, then every 6h. KV persists.', store: 'KV hedge_alerts_cache, beta_estimates',
    endpoints: ['/api/hedge-alerts', '/api/corr-history', '/api/hedge-signals'], health: ['corr'] },
  { id: 'yield_shape', name: '10-year intraday (yield shape)', provider: 'Yahoo Finance', category: 'crossasset',
    purpose: 'Intraday ^TNX bars for the yield-shape regime read.',
    details: '^TNX 15-minute bars.', refresh: 'Every 5 min. KV persists.', store: 'KV yield_shape_regime_v1',
    endpoints: ['/api/yield-shape-regime'], kvStamp: { key: 'yield_shape_regime_v1', cadenceDays: 1 } },
  { id: 'hmm_macro', name: 'HMM macro context', provider: 'FRED', category: 'crossasset',
    purpose: 'VIX, HY OAS and the 2s10s that label the HMM regime model’s macro backdrop.',
    details: 'VIXCLS, BAMLH0A0HYM2, DGS10, DGS2.', refresh: 'On boot, then every 6h. KV persists.',
    store: 'KV hmm5m_macro_context', endpoints: ['/api/hmm5m-v2', '/api/hmm1h-v2'],
    kvStamp: { key: 'hmm5m_macro_context', cadenceDays: 1 }, series: ['macro'] },

  // ── Desk outputs ─────────────────────────────────────────────────────────
  { id: 'eod_review', name: 'Evening written review', provider: 'Desk (LLM-written)', category: 'desk',
    purpose: 'The written end-of-day read — what happened, what held, what to watch tomorrow.',
    details: 'Assembled from the day’s feeds and written by the model.', refresh: 'Each evening. KV persists.',
    store: 'KV eod_review_v1', endpoints: ['/api/eod-review'], health: ['eodReview'] },
  { id: 'morning_brief', name: 'Morning brief', provider: 'Desk (LLM-written)', category: 'desk',
    purpose: 'The written morning read the Daily Brief opens with.',
    details: 'Built from most feeds on this map at the configured hour (Brief Config).', refresh: 'Daily at the configured hour. KV persists.',
    store: 'KV morning_brief_v1', endpoints: ['/api/morning-brief'],
    kvStamp: { key: 'morning_brief_v1', cadenceDays: 1, market: false } },
  { id: 'daily_snapshot', name: 'Daily desk snapshot', provider: 'Desk', category: 'desk',
    purpose: 'One stored record of the desk’s state each day, so later reviews compare against what was known then.',
    details: 'Per-pair state, regime, events.', refresh: 'Hourly (first run 8 min after boot). KV persists.',
    store: 'KV daily_snapshot_v1', endpoints: ['/api/daily-snapshot'],
    kvStamp: { key: 'daily_snapshot_v1', cadenceDays: 1, market: false } },
  { id: 'analogml', name: 'AnalogML motif trades', provider: 'Desk (AnalogML bot)', category: 'desk',
    purpose: 'The hourly structural-motif scan and its paper trades — the AnalogML trade log.',
    details: 'motif_trades.json / motif_state.json written hourly; the plan pushed to KV motif_bot_plan.',
    refresh: 'Hourly at :01 on Railway (motif_track_loop.sh).', store: 'R2 analogml/ · KV motif_bot_plan',
    endpoints: ['/api/analogml/motif-trades', '/api/analogml/motif-state'], consumers: 'motif_bot (KV motif_bot_plan)' },

  // ── Files & research pulls ───────────────────────────────────────────────
  { id: 'calendar_csv', name: 'Calendar archive 2014–2026', provider: 'Vendor export (manual)', category: 'files', kind: 'file',
    purpose: 'Twelve years of releases with actual/consensus — the in-sample/out-of-sample history for every news study.',
    details: 'calendar_events.csv (date, country, ccy, impact, event, actual, previous, consensus). Ends 2026-07; the live calendar tops it up.',
    refresh: 'Manual export.', store: 'calendar_events.csv', endpoints: ['/api/calendar-events'],
    consumers: 'scripts/build_surprise_backfill.mjs, build_event_response_book.mjs, forge/*.py' },
  { id: 'event_response', name: 'Event-response book', provider: 'Desk (offline build)', category: 'files', kind: 'file',
    purpose: 'How each pair actually moved after each release type — the event-response page and impact map.',
    details: 'backfill/event_response_book.json, _events, _clocks and surprise_backfill.json.',
    refresh: 'Rebuilt by scripts/build_event_response_book.mjs when someone runs it.', store: 'backfill/*.json',
    files: ['event-response.html'], consumers: 'js/eventImpactMap.js' },
  { id: 'ifo_seed', name: 'German ifo business climate', provider: 'ifo (hand-entered)', category: 'files', kind: 'file',
    purpose: 'The DAX factor’s German sentiment leg.',
    details: 'KV ifo_data (edited in the dashboard’s IFO modal) with ifo.json as a fallback — the file holds SEED values.',
    refresh: 'Manual, monthly.', store: 'KV ifo_data · ifo.json', files: ['index.html', 'indexv2.html'] },
  { id: 'research_pulls', name: 'On-demand research pulls', provider: 'FRED · Yahoo · Treasury', category: 'files',
    purpose: 'Series fetched only when a research page runs: global liquidity, net liquidity, the liquidity gate, macro-equity, carry, factor and lead-lag studies.',
    details: 'WALCL/TGA/RRP, NFCI, ISM/INDPRO, per-currency short rates, HY OAS, TLT/GLD/SPY/^GDAXI and others, each cached for a few hours.',
    refresh: 'On request only; nothing is kept between deploys.', store: 'GLI_BT_CACHE, NET_LIQ_CACHE, LIQ_GATE_FRED_CACHE, ME_RAW_CACHE (memory)',
    endpoints: ['/api/global-liquidity/backtest/run', '/api/liquidity-analysis/net-liquidity-nq/run', '/api/liquidity-gate/live', '/api/liquidity-gate/backtest', '/api/macro-equity-backtest/run', '/api/fx-carry', '/api/multi-factor/run', '/api/credit-leadlag/run', '/api/diversification/data', '/api/nasdaq-macro-lead/summary'],
    series: ['netLiquidity', 'liquidityGate', 'yieldSpread', 'carry', 'creditStress'] },
];
