/**
 * Tape-speed parameters — GENERATED by analysis/build_tape_speed_params.mjs, do not hand-edit.
 *
 * Per instrument and session band: quintile cut points of 15-minute speed (ATR per
 * minute) and, for each quintile, what the NEXT HOUR has historically looked like --
 * dwell (share of the hour within 0.10 ATR of where price was), the median next-hour
 * range in ATR, and the median ratio of next-hour to previous-hour range.
 *
 * Unconditional on levels, deliberately. analysis/approach_speed_control_study.mjs
 * showed the "slow arrival dwells on the level" effect is speed persistence and
 * appears identically at random non-level prices, so the read belongs to every bar.
 * Context for what kind of hour this is, never a direction call.
 *
 * Built 2026-09-12 from 5 years of M1, sampled every 5 minutes.
 */
export const TAPE_SPEED_PARAMS = {
 "eurusd": {
  "pair": "eurusd",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97161,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0033
    ],
    "quintiles": [
     {
      "n": 19434,
      "dwell": 0.9179,
      "nextRangeAtr": 0.1089,
      "volRatio": 1.131
     },
     {
      "n": 19432,
      "dwell": 0.9133,
      "nextRangeAtr": 0.1108,
      "volRatio": 1.1153
     },
     {
      "n": 19431,
      "dwell": 0.9059,
      "nextRangeAtr": 0.1148,
      "volRatio": 1.0897
     },
     {
      "n": 19432,
      "dwell": 0.8923,
      "nextRangeAtr": 0.1216,
      "volRatio": 1.036
     },
     {
      "n": 19432,
      "dwell": 0.8351,
      "nextRangeAtr": 0.1491,
      "volRatio": 0.9289
     }
    ],
    "medianNextRangeAtr": 0.1199
   },
   "london": {
    "n": 76894,
    "cuts": [
     0.0011,
     0.0022,
     0.0036,
     0.0057
    ],
    "quintiles": [
     {
      "n": 15379,
      "dwell": 0.774,
      "nextRangeAtr": 0.1861,
      "volRatio": 1.0738
     },
     {
      "n": 15380,
      "dwell": 0.7707,
      "nextRangeAtr": 0.1881,
      "volRatio": 1.0591
     },
     {
      "n": 15378,
      "dwell": 0.7637,
      "nextRangeAtr": 0.1908,
      "volRatio": 1.0224
     },
     {
      "n": 15378,
      "dwell": 0.7462,
      "nextRangeAtr": 0.1972,
      "volRatio": 0.9776
     },
     {
      "n": 15379,
      "dwell": 0.6972,
      "nextRangeAtr": 0.2229,
      "volRatio": 0.8525
     }
    ],
    "medianNextRangeAtr": 0.1966
   },
   "ny": {
    "n": 76874,
    "cuts": [
     0.0013,
     0.0027,
     0.0044,
     0.0071
    ],
    "quintiles": [
     {
      "n": 15375,
      "dwell": 0.7087,
      "nextRangeAtr": 0.2164,
      "volRatio": 1.0071
     },
     {
      "n": 15375,
      "dwell": 0.6985,
      "nextRangeAtr": 0.2201,
      "volRatio": 0.9968
     },
     {
      "n": 15374,
      "dwell": 0.6882,
      "nextRangeAtr": 0.2277,
      "volRatio": 0.9704
     },
     {
      "n": 15375,
      "dwell": 0.6631,
      "nextRangeAtr": 0.2434,
      "volRatio": 0.9167
     },
     {
      "n": 15375,
      "dwell": 0.5859,
      "nextRangeAtr": 0.2935,
      "volRatio": 0.7959
     }
    ],
    "medianNextRangeAtr": 0.2393
   },
   "late": {
    "n": 73858,
    "cuts": [
     0.0006,
     0.0012,
     0.0022,
     0.0037
    ],
    "quintiles": [
     {
      "n": 14772,
      "dwell": 0.9347,
      "nextRangeAtr": 0.0896,
      "volRatio": 0.9037
     },
     {
      "n": 14771,
      "dwell": 0.929,
      "nextRangeAtr": 0.0944,
      "volRatio": 0.8771
     },
     {
      "n": 14772,
      "dwell": 0.9184,
      "nextRangeAtr": 0.1013,
      "volRatio": 0.8446
     },
     {
      "n": 14772,
      "dwell": 0.8939,
      "nextRangeAtr": 0.1144,
      "volRatio": 0.8095
     },
     {
      "n": 14771,
      "dwell": 0.805,
      "nextRangeAtr": 0.1509,
      "volRatio": 0.734
     }
    ],
    "medianNextRangeAtr": 0.1086
   }
  }
 },
 "gbpusd": {
  "pair": "gbpusd",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 96857,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0034
    ],
    "quintiles": [
     {
      "n": 19372,
      "dwell": 0.9125,
      "nextRangeAtr": 0.1113,
      "volRatio": 1.1367
     },
     {
      "n": 19371,
      "dwell": 0.9093,
      "nextRangeAtr": 0.1127,
      "volRatio": 1.1277
     },
     {
      "n": 19371,
      "dwell": 0.9006,
      "nextRangeAtr": 0.1168,
      "volRatio": 1.1031
     },
     {
      "n": 19372,
      "dwell": 0.8877,
      "nextRangeAtr": 0.1227,
      "volRatio": 1.0475
     },
     {
      "n": 19371,
      "dwell": 0.8289,
      "nextRangeAtr": 0.1515,
      "volRatio": 0.9419
     }
    ],
    "medianNextRangeAtr": 0.1219
   },
   "london": {
    "n": 76878,
    "cuts": [
     0.0011,
     0.0023,
     0.0038,
     0.006
    ],
    "quintiles": [
     {
      "n": 15376,
      "dwell": 0.7504,
      "nextRangeAtr": 0.1977,
      "volRatio": 1.0769
     },
     {
      "n": 15375,
      "dwell": 0.7432,
      "nextRangeAtr": 0.201,
      "volRatio": 1.0626
     },
     {
      "n": 15376,
      "dwell": 0.7375,
      "nextRangeAtr": 0.2033,
      "volRatio": 1.0257
     },
     {
      "n": 15375,
      "dwell": 0.7286,
      "nextRangeAtr": 0.2103,
      "volRatio": 0.9699
     },
     {
      "n": 15376,
      "dwell": 0.6781,
      "nextRangeAtr": 0.2328,
      "volRatio": 0.8486
     }
    ],
    "medianNextRangeAtr": 0.2092
   },
   "ny": {
    "n": 76869,
    "cuts": [
     0.0013,
     0.0027,
     0.0044,
     0.0072
    ],
    "quintiles": [
     {
      "n": 15374,
      "dwell": 0.7017,
      "nextRangeAtr": 0.2212,
      "volRatio": 1.0111
     },
     {
      "n": 15374,
      "dwell": 0.6984,
      "nextRangeAtr": 0.2225,
      "volRatio": 0.9962
     },
     {
      "n": 15373,
      "dwell": 0.6827,
      "nextRangeAtr": 0.2318,
      "volRatio": 0.9636
     },
     {
      "n": 15374,
      "dwell": 0.6609,
      "nextRangeAtr": 0.2449,
      "volRatio": 0.9125
     },
     {
      "n": 15374,
      "dwell": 0.5868,
      "nextRangeAtr": 0.2898,
      "volRatio": 0.8071
     }
    ],
    "medianNextRangeAtr": 0.2416
   },
   "late": {
    "n": 73451,
    "cuts": [
     0.0006,
     0.0013,
     0.0022,
     0.0037
    ],
    "quintiles": [
     {
      "n": 14691,
      "dwell": 0.9338,
      "nextRangeAtr": 0.0966,
      "volRatio": 0.9187
     },
     {
      "n": 14691,
      "dwell": 0.9281,
      "nextRangeAtr": 0.1,
      "volRatio": 0.8852
     },
     {
      "n": 14689,
      "dwell": 0.9157,
      "nextRangeAtr": 0.1071,
      "volRatio": 0.8689
     },
     {
      "n": 14690,
      "dwell": 0.8916,
      "nextRangeAtr": 0.1187,
      "volRatio": 0.8263
     },
     {
      "n": 14690,
      "dwell": 0.8102,
      "nextRangeAtr": 0.1522,
      "volRatio": 0.7487
     }
    ],
    "medianNextRangeAtr": 0.1135
   }
  }
 },
 "usdjpy": {
  "pair": "usdjpy",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97349,
    "cuts": [
     0.0007,
     0.0015,
     0.0026,
     0.0043
    ],
    "quintiles": [
     {
      "n": 19471,
      "dwell": 0.8764,
      "nextRangeAtr": 0.1292,
      "volRatio": 1.0596
     },
     {
      "n": 19469,
      "dwell": 0.8711,
      "nextRangeAtr": 0.1322,
      "volRatio": 1.033
     },
     {
      "n": 19469,
      "dwell": 0.8557,
      "nextRangeAtr": 0.142,
      "volRatio": 0.9944
     },
     {
      "n": 19470,
      "dwell": 0.8307,
      "nextRangeAtr": 0.1543,
      "volRatio": 0.9468
     },
     {
      "n": 19470,
      "dwell": 0.754,
      "nextRangeAtr": 0.192,
      "volRatio": 0.8278
     }
    ],
    "medianNextRangeAtr": 0.1488
   },
   "london": {
    "n": 76899,
    "cuts": [
     0.0008,
     0.0017,
     0.0029,
     0.0047
    ],
    "quintiles": [
     {
      "n": 15380,
      "dwell": 0.8557,
      "nextRangeAtr": 0.1422,
      "volRatio": 1.031
     },
     {
      "n": 15380,
      "dwell": 0.844,
      "nextRangeAtr": 0.1471,
      "volRatio": 1.0128
     },
     {
      "n": 15379,
      "dwell": 0.8316,
      "nextRangeAtr": 0.1546,
      "volRatio": 0.9819
     },
     {
      "n": 15380,
      "dwell": 0.8091,
      "nextRangeAtr": 0.1678,
      "volRatio": 0.9277
     },
     {
      "n": 15380,
      "dwell": 0.7292,
      "nextRangeAtr": 0.2061,
      "volRatio": 0.8218
     }
    ],
    "medianNextRangeAtr": 0.1623
   },
   "ny": {
    "n": 76872,
    "cuts": [
     0.001,
     0.0021,
     0.0036,
     0.006
    ],
    "quintiles": [
     {
      "n": 15375,
      "dwell": 0.7907,
      "nextRangeAtr": 0.1684,
      "volRatio": 1
     },
     {
      "n": 15374,
      "dwell": 0.7802,
      "nextRangeAtr": 0.1739,
      "volRatio": 0.9788
     },
     {
      "n": 15375,
      "dwell": 0.7616,
      "nextRangeAtr": 0.1861,
      "volRatio": 0.946
     },
     {
      "n": 15373,
      "dwell": 0.7301,
      "nextRangeAtr": 0.205,
      "volRatio": 0.8898
     },
     {
      "n": 15375,
      "dwell": 0.6261,
      "nextRangeAtr": 0.2624,
      "volRatio": 0.7719
     }
    ],
    "medianNextRangeAtr": 0.1981
   },
   "late": {
    "n": 74017,
    "cuts": [
     0.0005,
     0.0011,
     0.0019,
     0.0032
    ],
    "quintiles": [
     {
      "n": 14804,
      "dwell": 0.9448,
      "nextRangeAtr": 0.0875,
      "volRatio": 1.0053
     },
     {
      "n": 14803,
      "dwell": 0.9401,
      "nextRangeAtr": 0.0904,
      "volRatio": 0.953
     },
     {
      "n": 14803,
      "dwell": 0.9336,
      "nextRangeAtr": 0.0951,
      "volRatio": 0.9147
     },
     {
      "n": 14803,
      "dwell": 0.9158,
      "nextRangeAtr": 0.1061,
      "volRatio": 0.8736
     },
     {
      "n": 14804,
      "dwell": 0.8333,
      "nextRangeAtr": 0.1383,
      "volRatio": 0.7599
     }
    ],
    "medianNextRangeAtr": 0.1023
   }
  }
 },
 "audusd": {
  "pair": "audusd",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 96621,
    "cuts": [
     0.0009,
     0.0018,
     0.003,
     0.0048
    ],
    "quintiles": [
     {
      "n": 19325,
      "dwell": 0.825,
      "nextRangeAtr": 0.1559,
      "volRatio": 1.0999
     },
     {
      "n": 19326,
      "dwell": 0.8212,
      "nextRangeAtr": 0.1582,
      "volRatio": 1.0742
     },
     {
      "n": 19323,
      "dwell": 0.8108,
      "nextRangeAtr": 0.1625,
      "volRatio": 1.0385
     },
     {
      "n": 19323,
      "dwell": 0.7994,
      "nextRangeAtr": 0.1685,
      "volRatio": 0.9848
     },
     {
      "n": 19324,
      "dwell": 0.748,
      "nextRangeAtr": 0.1925,
      "volRatio": 0.8382
     }
    ],
    "medianNextRangeAtr": 0.1672
   },
   "london": {
    "n": 76716,
    "cuts": [
     0.0009,
     0.002,
     0.0032,
     0.005
    ],
    "quintiles": [
     {
      "n": 15344,
      "dwell": 0.8157,
      "nextRangeAtr": 0.1624,
      "volRatio": 1.044
     },
     {
      "n": 15345,
      "dwell": 0.8132,
      "nextRangeAtr": 0.1647,
      "volRatio": 1.0278
     },
     {
      "n": 15341,
      "dwell": 0.8093,
      "nextRangeAtr": 0.166,
      "volRatio": 1
     },
     {
      "n": 15343,
      "dwell": 0.7962,
      "nextRangeAtr": 0.1722,
      "volRatio": 0.9503
     },
     {
      "n": 15343,
      "dwell": 0.7512,
      "nextRangeAtr": 0.1908,
      "volRatio": 0.8375
     }
    ],
    "medianNextRangeAtr": 0.171
   },
   "ny": {
    "n": 76786,
    "cuts": [
     0.0012,
     0.0024,
     0.0041,
     0.0066
    ],
    "quintiles": [
     {
      "n": 15359,
      "dwell": 0.7388,
      "nextRangeAtr": 0.1995,
      "volRatio": 1.0358
     },
     {
      "n": 15356,
      "dwell": 0.7266,
      "nextRangeAtr": 0.2061,
      "volRatio": 1.0311
     },
     {
      "n": 15357,
      "dwell": 0.7158,
      "nextRangeAtr": 0.21,
      "volRatio": 0.9872
     },
     {
      "n": 15357,
      "dwell": 0.689,
      "nextRangeAtr": 0.2272,
      "volRatio": 0.9286
     },
     {
      "n": 15357,
      "dwell": 0.6073,
      "nextRangeAtr": 0.2713,
      "volRatio": 0.8
     }
    ],
    "medianNextRangeAtr": 0.2221
   },
   "late": {
    "n": 71883,
    "cuts": [
     0.0006,
     0.0013,
     0.0022,
     0.0037
    ],
    "quintiles": [
     {
      "n": 14377,
      "dwell": 0.932,
      "nextRangeAtr": 0.0997,
      "volRatio": 0.9643
     },
     {
      "n": 14378,
      "dwell": 0.9257,
      "nextRangeAtr": 0.1035,
      "volRatio": 0.93
     },
     {
      "n": 14375,
      "dwell": 0.9156,
      "nextRangeAtr": 0.1077,
      "volRatio": 0.9
     },
     {
      "n": 14376,
      "dwell": 0.8909,
      "nextRangeAtr": 0.1188,
      "volRatio": 0.8571
     },
     {
      "n": 14377,
      "dwell": 0.7998,
      "nextRangeAtr": 0.1524,
      "volRatio": 0.7613
     }
    ],
    "medianNextRangeAtr": 0.1151
   }
  }
 },
 "usdchf": {
  "pair": "usdchf",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 94037,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0034
    ],
    "quintiles": [
     {
      "n": 18809,
      "dwell": 0.911,
      "nextRangeAtr": 0.1098,
      "volRatio": 1.1333
     },
     {
      "n": 18806,
      "dwell": 0.9114,
      "nextRangeAtr": 0.111,
      "volRatio": 1.111
     },
     {
      "n": 18807,
      "dwell": 0.9019,
      "nextRangeAtr": 0.116,
      "volRatio": 1.0799
     },
     {
      "n": 18807,
      "dwell": 0.8858,
      "nextRangeAtr": 0.1245,
      "volRatio": 1.0333
     },
     {
      "n": 18808,
      "dwell": 0.8214,
      "nextRangeAtr": 0.1545,
      "volRatio": 0.9322
     }
    ],
    "medianNextRangeAtr": 0.1222
   },
   "london": {
    "n": 76736,
    "cuts": [
     0.0011,
     0.0022,
     0.0037,
     0.0059
    ],
    "quintiles": [
     {
      "n": 15348,
      "dwell": 0.7666,
      "nextRangeAtr": 0.1903,
      "volRatio": 1.0714
     },
     {
      "n": 15347,
      "dwell": 0.7601,
      "nextRangeAtr": 0.1925,
      "volRatio": 1.0602
     },
     {
      "n": 15347,
      "dwell": 0.7462,
      "nextRangeAtr": 0.1966,
      "volRatio": 1.0394
     },
     {
      "n": 15347,
      "dwell": 0.7322,
      "nextRangeAtr": 0.2064,
      "volRatio": 0.9816
     },
     {
      "n": 15347,
      "dwell": 0.6727,
      "nextRangeAtr": 0.2318,
      "volRatio": 0.8446
     }
    ],
    "medianNextRangeAtr": 0.2032
   },
   "ny": {
    "n": 76781,
    "cuts": [
     0.0013,
     0.0027,
     0.0045,
     0.0074
    ],
    "quintiles": [
     {
      "n": 15358,
      "dwell": 0.7052,
      "nextRangeAtr": 0.2177,
      "volRatio": 0.9959
     },
     {
      "n": 15356,
      "dwell": 0.6927,
      "nextRangeAtr": 0.2244,
      "volRatio": 0.9999
     },
     {
      "n": 15355,
      "dwell": 0.6811,
      "nextRangeAtr": 0.2314,
      "volRatio": 0.9591
     },
     {
      "n": 15356,
      "dwell": 0.6472,
      "nextRangeAtr": 0.2499,
      "volRatio": 0.9132
     },
     {
      "n": 15356,
      "dwell": 0.5756,
      "nextRangeAtr": 0.2991,
      "volRatio": 0.8043
     }
    ],
    "medianNextRangeAtr": 0.2436
   },
   "late": {
    "n": 70458,
    "cuts": [
     0.0006,
     0.0014,
     0.0023,
     0.0039
    ],
    "quintiles": [
     {
      "n": 14092,
      "dwell": 0.9213,
      "nextRangeAtr": 0.1129,
      "volRatio": 0.9729
     },
     {
      "n": 14091,
      "dwell": 0.915,
      "nextRangeAtr": 0.1155,
      "volRatio": 0.9523
     },
     {
      "n": 14092,
      "dwell": 0.9057,
      "nextRangeAtr": 0.1194,
      "volRatio": 0.919
     },
     {
      "n": 14091,
      "dwell": 0.8821,
      "nextRangeAtr": 0.1291,
      "volRatio": 0.8647
     },
     {
      "n": 14092,
      "dwell": 0.8046,
      "nextRangeAtr": 0.1581,
      "volRatio": 0.7625
     }
    ],
    "medianNextRangeAtr": 0.1262
   }
  }
 },
 "euraud": {
  "pair": "euraud",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97186,
    "cuts": [
     0.0009,
     0.0019,
     0.0031,
     0.005
    ],
    "quintiles": [
     {
      "n": 19440,
      "dwell": 0.8181,
      "nextRangeAtr": 0.1621,
      "volRatio": 1.0954
     },
     {
      "n": 19435,
      "dwell": 0.8155,
      "nextRangeAtr": 0.1638,
      "volRatio": 1.0678
     },
     {
      "n": 19437,
      "dwell": 0.8015,
      "nextRangeAtr": 0.1697,
      "volRatio": 1.0489
     },
     {
      "n": 19437,
      "dwell": 0.7848,
      "nextRangeAtr": 0.1761,
      "volRatio": 0.9931
     },
     {
      "n": 19437,
      "dwell": 0.7291,
      "nextRangeAtr": 0.2039,
      "volRatio": 0.8429
     }
    ],
    "medianNextRangeAtr": 0.1745
   },
   "london": {
    "n": 76891,
    "cuts": [
     0.001,
     0.0021,
     0.0034,
     0.0054
    ],
    "quintiles": [
     {
      "n": 15380,
      "dwell": 0.7875,
      "nextRangeAtr": 0.1789,
      "volRatio": 1.0467
     },
     {
      "n": 15377,
      "dwell": 0.7876,
      "nextRangeAtr": 0.179,
      "volRatio": 1.0329
     },
     {
      "n": 15379,
      "dwell": 0.7792,
      "nextRangeAtr": 0.1829,
      "volRatio": 1.0052
     },
     {
      "n": 15377,
      "dwell": 0.7643,
      "nextRangeAtr": 0.1901,
      "volRatio": 0.951
     },
     {
      "n": 15378,
      "dwell": 0.7172,
      "nextRangeAtr": 0.2116,
      "volRatio": 0.8414
     }
    ],
    "medianNextRangeAtr": 0.188
   },
   "ny": {
    "n": 76882,
    "cuts": [
     0.0011,
     0.0024,
     0.0039,
     0.0064
    ],
    "quintiles": [
     {
      "n": 15377,
      "dwell": 0.7532,
      "nextRangeAtr": 0.1958,
      "volRatio": 1.0138
     },
     {
      "n": 15376,
      "dwell": 0.7515,
      "nextRangeAtr": 0.1982,
      "volRatio": 0.9926
     },
     {
      "n": 15376,
      "dwell": 0.7322,
      "nextRangeAtr": 0.2084,
      "volRatio": 0.9941
     },
     {
      "n": 15376,
      "dwell": 0.7032,
      "nextRangeAtr": 0.2235,
      "volRatio": 0.9415
     },
     {
      "n": 15377,
      "dwell": 0.6334,
      "nextRangeAtr": 0.2589,
      "volRatio": 0.8163
     }
    ],
    "medianNextRangeAtr": 0.2166
   },
   "late": {
    "n": 74837,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0035
    ],
    "quintiles": [
     {
      "n": 14969,
      "dwell": 0.9377,
      "nextRangeAtr": 0.1085,
      "volRatio": 1.0091
     },
     {
      "n": 14967,
      "dwell": 0.9375,
      "nextRangeAtr": 0.1088,
      "volRatio": 0.9791
     },
     {
      "n": 14966,
      "dwell": 0.9273,
      "nextRangeAtr": 0.1142,
      "volRatio": 0.9572
     },
     {
      "n": 14967,
      "dwell": 0.9169,
      "nextRangeAtr": 0.12,
      "volRatio": 0.9079
     },
     {
      "n": 14968,
      "dwell": 0.8422,
      "nextRangeAtr": 0.1477,
      "volRatio": 0.8063
     }
    ],
    "medianNextRangeAtr": 0.1192
   }
  }
 },
 "eurchf": {
  "pair": "eurchf",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 95314,
    "cuts": [
     0.0005,
     0.0012,
     0.002,
     0.0033
    ],
    "quintiles": [
     {
      "n": 19063,
      "dwell": 0.9249,
      "nextRangeAtr": 0.102,
      "volRatio": 1.1428
     },
     {
      "n": 19064,
      "dwell": 0.9215,
      "nextRangeAtr": 0.1045,
      "volRatio": 1.1191
     },
     {
      "n": 19061,
      "dwell": 0.9112,
      "nextRangeAtr": 0.1097,
      "volRatio": 1.1011
     },
     {
      "n": 19065,
      "dwell": 0.8933,
      "nextRangeAtr": 0.1205,
      "volRatio": 1.0645
     },
     {
      "n": 19061,
      "dwell": 0.8096,
      "nextRangeAtr": 0.159,
      "volRatio": 0.9865
     }
    ],
    "medianNextRangeAtr": 0.117
   },
   "london": {
    "n": 76850,
    "cuts": [
     0.0012,
     0.0026,
     0.0042,
     0.0068
    ],
    "quintiles": [
     {
      "n": 15370,
      "dwell": 0.7165,
      "nextRangeAtr": 0.2157,
      "volRatio": 1.0547
     },
     {
      "n": 15370,
      "dwell": 0.7112,
      "nextRangeAtr": 0.2183,
      "volRatio": 1.0456
     },
     {
      "n": 15370,
      "dwell": 0.7004,
      "nextRangeAtr": 0.2234,
      "volRatio": 1.0109
     },
     {
      "n": 15370,
      "dwell": 0.6762,
      "nextRangeAtr": 0.235,
      "volRatio": 0.9709
     },
     {
      "n": 15370,
      "dwell": 0.6152,
      "nextRangeAtr": 0.2716,
      "volRatio": 0.8333
     }
    ],
    "medianNextRangeAtr": 0.2323
   },
   "ny": {
    "n": 76814,
    "cuts": [
     0.0012,
     0.0026,
     0.0044,
     0.0071
    ],
    "quintiles": [
     {
      "n": 15363,
      "dwell": 0.7181,
      "nextRangeAtr": 0.2142,
      "volRatio": 0.9853
     },
     {
      "n": 15364,
      "dwell": 0.7114,
      "nextRangeAtr": 0.2188,
      "volRatio": 0.9878
     },
     {
      "n": 15361,
      "dwell": 0.6949,
      "nextRangeAtr": 0.2293,
      "volRatio": 0.9722
     },
     {
      "n": 15363,
      "dwell": 0.6699,
      "nextRangeAtr": 0.244,
      "volRatio": 0.9208
     },
     {
      "n": 15363,
      "dwell": 0.5905,
      "nextRangeAtr": 0.2887,
      "volRatio": 0.8317
     }
    ],
    "medianNextRangeAtr": 0.2389
   },
   "late": {
    "n": 71843,
    "cuts": [
     0.0007,
     0.0014,
     0.0023,
     0.0038
    ],
    "quintiles": [
     {
      "n": 14370,
      "dwell": 0.9217,
      "nextRangeAtr": 0.1191,
      "volRatio": 1
     },
     {
      "n": 14367,
      "dwell": 0.9169,
      "nextRangeAtr": 0.1213,
      "volRatio": 0.9864
     },
     {
      "n": 14371,
      "dwell": 0.9136,
      "nextRangeAtr": 0.1248,
      "volRatio": 0.9584
     },
     {
      "n": 14366,
      "dwell": 0.8931,
      "nextRangeAtr": 0.1321,
      "volRatio": 0.9124
     },
     {
      "n": 14369,
      "dwell": 0.8219,
      "nextRangeAtr": 0.1581,
      "volRatio": 0.7955
     }
    ],
    "medianNextRangeAtr": 0.1306
   }
  }
 },
 "audjpy": {
  "pair": "audjpy",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97366,
    "cuts": [
     0.0009,
     0.0019,
     0.0031,
     0.005
    ],
    "quintiles": [
     {
      "n": 19475,
      "dwell": 0.8197,
      "nextRangeAtr": 0.1605,
      "volRatio": 1.0619
     },
     {
      "n": 19472,
      "dwell": 0.8124,
      "nextRangeAtr": 0.1636,
      "volRatio": 1.0565
     },
     {
      "n": 19473,
      "dwell": 0.8065,
      "nextRangeAtr": 0.1672,
      "volRatio": 1.0152
     },
     {
      "n": 19473,
      "dwell": 0.7848,
      "nextRangeAtr": 0.178,
      "volRatio": 0.9678
     },
     {
      "n": 19473,
      "dwell": 0.7167,
      "nextRangeAtr": 0.2108,
      "volRatio": 0.8188
     }
    ],
    "medianNextRangeAtr": 0.1749
   },
   "london": {
    "n": 76895,
    "cuts": [
     0.0009,
     0.0019,
     0.0031,
     0.005
    ],
    "quintiles": [
     {
      "n": 15379,
      "dwell": 0.8328,
      "nextRangeAtr": 0.1547,
      "volRatio": 1.0281
     },
     {
      "n": 15379,
      "dwell": 0.8315,
      "nextRangeAtr": 0.1562,
      "volRatio": 1.0059
     },
     {
      "n": 15379,
      "dwell": 0.8206,
      "nextRangeAtr": 0.1633,
      "volRatio": 0.9796
     },
     {
      "n": 15379,
      "dwell": 0.8,
      "nextRangeAtr": 0.172,
      "volRatio": 0.9345
     },
     {
      "n": 15379,
      "dwell": 0.7283,
      "nextRangeAtr": 0.2043,
      "volRatio": 0.8182
     }
    ],
    "medianNextRangeAtr": 0.169
   },
   "ny": {
    "n": 76881,
    "cuts": [
     0.001,
     0.0021,
     0.0036,
     0.0059
    ],
    "quintiles": [
     {
      "n": 15379,
      "dwell": 0.7902,
      "nextRangeAtr": 0.1754,
      "volRatio": 1.0225
     },
     {
      "n": 15374,
      "dwell": 0.7775,
      "nextRangeAtr": 0.1824,
      "volRatio": 1.0217
     },
     {
      "n": 15376,
      "dwell": 0.7641,
      "nextRangeAtr": 0.19,
      "volRatio": 0.9931
     },
     {
      "n": 15376,
      "dwell": 0.7329,
      "nextRangeAtr": 0.2064,
      "volRatio": 0.9444
     },
     {
      "n": 15376,
      "dwell": 0.6488,
      "nextRangeAtr": 0.2501,
      "volRatio": 0.8234
     }
    ],
    "medianNextRangeAtr": 0.1999
   },
   "late": {
    "n": 75157,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0035
    ],
    "quintiles": [
     {
      "n": 15032,
      "dwell": 0.9286,
      "nextRangeAtr": 0.1051,
      "volRatio": 1.0159
     },
     {
      "n": 15033,
      "dwell": 0.9267,
      "nextRangeAtr": 0.1078,
      "volRatio": 0.9999
     },
     {
      "n": 15030,
      "dwell": 0.9171,
      "nextRangeAtr": 0.1128,
      "volRatio": 0.96
     },
     {
      "n": 15030,
      "dwell": 0.9025,
      "nextRangeAtr": 0.12,
      "volRatio": 0.9064
     },
     {
      "n": 15032,
      "dwell": 0.8197,
      "nextRangeAtr": 0.1521,
      "volRatio": 0.8004
     }
    ],
    "medianNextRangeAtr": 0.1181
   }
  }
 },
 "cadjpy": {
  "pair": "cadjpy",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97200,
    "cuts": [
     0.0007,
     0.0015,
     0.0025,
     0.0041
    ],
    "quintiles": [
     {
      "n": 19440,
      "dwell": 0.8797,
      "nextRangeAtr": 0.1283,
      "volRatio": 1.0616
     },
     {
      "n": 19440,
      "dwell": 0.8737,
      "nextRangeAtr": 0.1317,
      "volRatio": 1.0435
     },
     {
      "n": 19440,
      "dwell": 0.8652,
      "nextRangeAtr": 0.138,
      "volRatio": 1.0148
     },
     {
      "n": 19441,
      "dwell": 0.8421,
      "nextRangeAtr": 0.1478,
      "volRatio": 0.9562
     },
     {
      "n": 19439,
      "dwell": 0.7709,
      "nextRangeAtr": 0.1836,
      "volRatio": 0.8367
     }
    ],
    "medianNextRangeAtr": 0.1444
   },
   "london": {
    "n": 76865,
    "cuts": [
     0.0009,
     0.0018,
     0.003,
     0.0049
    ],
    "quintiles": [
     {
      "n": 15374,
      "dwell": 0.8374,
      "nextRangeAtr": 0.1522,
      "volRatio": 1.0503
     },
     {
      "n": 15372,
      "dwell": 0.8312,
      "nextRangeAtr": 0.154,
      "volRatio": 1.0378
     },
     {
      "n": 15373,
      "dwell": 0.8214,
      "nextRangeAtr": 0.1606,
      "volRatio": 1.0213
     },
     {
      "n": 15373,
      "dwell": 0.7989,
      "nextRangeAtr": 0.1713,
      "volRatio": 0.9612
     },
     {
      "n": 15373,
      "dwell": 0.7268,
      "nextRangeAtr": 0.2042,
      "volRatio": 0.8305
     }
    ],
    "medianNextRangeAtr": 0.1677
   },
   "ny": {
    "n": 76870,
    "cuts": [
     0.0011,
     0.0023,
     0.0039,
     0.0064
    ],
    "quintiles": [
     {
      "n": 15374,
      "dwell": 0.7555,
      "nextRangeAtr": 0.1911,
      "volRatio": 1.0258
     },
     {
      "n": 15374,
      "dwell": 0.7442,
      "nextRangeAtr": 0.1983,
      "volRatio": 1.0138
     },
     {
      "n": 15374,
      "dwell": 0.7266,
      "nextRangeAtr": 0.2046,
      "volRatio": 0.9831
     },
     {
      "n": 15374,
      "dwell": 0.696,
      "nextRangeAtr": 0.2229,
      "volRatio": 0.9343
     },
     {
      "n": 15374,
      "dwell": 0.6199,
      "nextRangeAtr": 0.2699,
      "volRatio": 0.8073
     }
    ],
    "medianNextRangeAtr": 0.2162
   },
   "late": {
    "n": 74229,
    "cuts": [
     0.0006,
     0.0013,
     0.0022,
     0.0037
    ],
    "quintiles": [
     {
      "n": 14847,
      "dwell": 0.9241,
      "nextRangeAtr": 0.1079,
      "volRatio": 0.9865
     },
     {
      "n": 14845,
      "dwell": 0.9209,
      "nextRangeAtr": 0.1096,
      "volRatio": 0.9751
     },
     {
      "n": 14846,
      "dwell": 0.9109,
      "nextRangeAtr": 0.1141,
      "volRatio": 0.9278
     },
     {
      "n": 14845,
      "dwell": 0.8939,
      "nextRangeAtr": 0.1234,
      "volRatio": 0.885
     },
     {
      "n": 14846,
      "dwell": 0.8116,
      "nextRangeAtr": 0.1568,
      "volRatio": 0.7979
     }
    ],
    "medianNextRangeAtr": 0.1208
   }
  }
 },
 "chfjpy": {
  "pair": "chfjpy",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1282
  },
  "bands": {
   "asia": {
    "n": 97324,
    "cuts": [
     0.0007,
     0.0015,
     0.0026,
     0.0043
    ],
    "quintiles": [
     {
      "n": 19465,
      "dwell": 0.8743,
      "nextRangeAtr": 0.1342,
      "volRatio": 1.0882
     },
     {
      "n": 19466,
      "dwell": 0.8654,
      "nextRangeAtr": 0.1391,
      "volRatio": 1.0831
     },
     {
      "n": 19463,
      "dwell": 0.8568,
      "nextRangeAtr": 0.1434,
      "volRatio": 1.0397
     },
     {
      "n": 19465,
      "dwell": 0.8336,
      "nextRangeAtr": 0.1553,
      "volRatio": 0.9883
     },
     {
      "n": 19465,
      "dwell": 0.7596,
      "nextRangeAtr": 0.1931,
      "volRatio": 0.8693
     }
    ],
    "medianNextRangeAtr": 0.1516
   },
   "london": {
    "n": 76904,
    "cuts": [
     0.0011,
     0.0022,
     0.0037,
     0.0059
    ],
    "quintiles": [
     {
      "n": 15381,
      "dwell": 0.7755,
      "nextRangeAtr": 0.185,
      "volRatio": 1.0386
     },
     {
      "n": 15381,
      "dwell": 0.7694,
      "nextRangeAtr": 0.1891,
      "volRatio": 1.0299
     },
     {
      "n": 15380,
      "dwell": 0.7543,
      "nextRangeAtr": 0.1958,
      "volRatio": 0.9932
     },
     {
      "n": 15381,
      "dwell": 0.7318,
      "nextRangeAtr": 0.2082,
      "volRatio": 0.9565
     },
     {
      "n": 15381,
      "dwell": 0.6603,
      "nextRangeAtr": 0.2451,
      "volRatio": 0.8357
     }
    ],
    "medianNextRangeAtr": 0.2034
   },
   "ny": {
    "n": 76870,
    "cuts": [
     0.0011,
     0.0023,
     0.0038,
     0.0062
    ],
    "quintiles": [
     {
      "n": 15374,
      "dwell": 0.7686,
      "nextRangeAtr": 0.1877,
      "volRatio": 0.9927
     },
     {
      "n": 15374,
      "dwell": 0.7623,
      "nextRangeAtr": 0.1918,
      "volRatio": 0.9773
     },
     {
      "n": 15374,
      "dwell": 0.7438,
      "nextRangeAtr": 0.2007,
      "volRatio": 0.9583
     },
     {
      "n": 15374,
      "dwell": 0.7191,
      "nextRangeAtr": 0.2155,
      "volRatio": 0.9187
     },
     {
      "n": 15374,
      "dwell": 0.6401,
      "nextRangeAtr": 0.2579,
      "volRatio": 0.8155
     }
    ],
    "medianNextRangeAtr": 0.2101
   },
   "late": {
    "n": 73387,
    "cuts": [
     0.0006,
     0.0013,
     0.0021,
     0.0035
    ],
    "quintiles": [
     {
      "n": 14679,
      "dwell": 0.9318,
      "nextRangeAtr": 0.1127,
      "volRatio": 1.0414
     },
     {
      "n": 14676,
      "dwell": 0.9264,
      "nextRangeAtr": 0.1153,
      "volRatio": 1.026
     },
     {
      "n": 14677,
      "dwell": 0.9226,
      "nextRangeAtr": 0.1178,
      "volRatio": 0.9938
     },
     {
      "n": 14678,
      "dwell": 0.9073,
      "nextRangeAtr": 0.1255,
      "volRatio": 0.9379
     },
     {
      "n": 14677,
      "dwell": 0.8372,
      "nextRangeAtr": 0.1518,
      "volRatio": 0.8282
     }
    ],
    "medianNextRangeAtr": 0.124
   }
  }
 },
 "gold": {
  "pair": "gold",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1275
  },
  "bands": {
   "asia": {
    "n": 96758,
    "cuts": [
     0.0007,
     0.0014,
     0.0024,
     0.0039
    ],
    "quintiles": [
     {
      "n": 19352,
      "dwell": 0.8875,
      "nextRangeAtr": 0.127,
      "volRatio": 1.1122
     },
     {
      "n": 19351,
      "dwell": 0.8827,
      "nextRangeAtr": 0.1291,
      "volRatio": 1.0884
     },
     {
      "n": 19352,
      "dwell": 0.8756,
      "nextRangeAtr": 0.1335,
      "volRatio": 1.0577
     },
     {
      "n": 19351,
      "dwell": 0.859,
      "nextRangeAtr": 0.14,
      "volRatio": 0.9833
     },
     {
      "n": 19352,
      "dwell": 0.7961,
      "nextRangeAtr": 0.1679,
      "volRatio": 0.8458
     }
    ],
    "medianNextRangeAtr": 0.1387
   },
   "london": {
    "n": 76472,
    "cuts": [
     0.0008,
     0.0017,
     0.0028,
     0.0045
    ],
    "quintiles": [
     {
      "n": 15295,
      "dwell": 0.8483,
      "nextRangeAtr": 0.1514,
      "volRatio": 1.0932
     },
     {
      "n": 15294,
      "dwell": 0.846,
      "nextRangeAtr": 0.1516,
      "volRatio": 1.0639
     },
     {
      "n": 15294,
      "dwell": 0.8356,
      "nextRangeAtr": 0.156,
      "volRatio": 1.0388
     },
     {
      "n": 15295,
      "dwell": 0.8197,
      "nextRangeAtr": 0.1644,
      "volRatio": 0.9929
     },
     {
      "n": 15294,
      "dwell": 0.7671,
      "nextRangeAtr": 0.1861,
      "volRatio": 0.8596
     }
    ],
    "medianNextRangeAtr": 0.1615
   },
   "ny": {
    "n": 76422,
    "cuts": [
     0.0012,
     0.0025,
     0.0043,
     0.0071
    ],
    "quintiles": [
     {
      "n": 15285,
      "dwell": 0.7346,
      "nextRangeAtr": 0.2068,
      "volRatio": 1.0274
     },
     {
      "n": 15284,
      "dwell": 0.7228,
      "nextRangeAtr": 0.2142,
      "volRatio": 1.0108
     },
     {
      "n": 15284,
      "dwell": 0.702,
      "nextRangeAtr": 0.2266,
      "volRatio": 0.9676
     },
     {
      "n": 15284,
      "dwell": 0.6663,
      "nextRangeAtr": 0.2489,
      "volRatio": 0.9196
     },
     {
      "n": 15285,
      "dwell": 0.5653,
      "nextRangeAtr": 0.3113,
      "volRatio": 0.7936
     }
    ],
    "medianNextRangeAtr": 0.2402
   },
   "late": {
    "n": 61673,
    "cuts": [
     0.0006,
     0.0014,
     0.0023,
     0.0039
    ],
    "quintiles": [
     {
      "n": 12335,
      "dwell": 0.9195,
      "nextRangeAtr": 0.1024,
      "volRatio": 0.9015
     },
     {
      "n": 12335,
      "dwell": 0.9111,
      "nextRangeAtr": 0.1056,
      "volRatio": 0.886
     },
     {
      "n": 12334,
      "dwell": 0.9004,
      "nextRangeAtr": 0.112,
      "volRatio": 0.8746
     },
     {
      "n": 12334,
      "dwell": 0.8813,
      "nextRangeAtr": 0.1238,
      "volRatio": 0.8292
     },
     {
      "n": 12335,
      "dwell": 0.7929,
      "nextRangeAtr": 0.159,
      "volRatio": 0.7453
     }
    ],
    "medianNextRangeAtr": 0.119
   }
  }
 },
 "nq": {
  "pair": "nq",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1277
  },
  "bands": {
   "asia": {
    "n": 95407,
    "cuts": [
     0.0004,
     0.0009,
     0.0015,
     0.0025
    ],
    "quintiles": [
     {
      "n": 19082,
      "dwell": 0.9636,
      "nextRangeAtr": 0.0743,
      "volRatio": 1.0909
     },
     {
      "n": 19082,
      "dwell": 0.9612,
      "nextRangeAtr": 0.0769,
      "volRatio": 1.0706
     },
     {
      "n": 19080,
      "dwell": 0.9548,
      "nextRangeAtr": 0.0808,
      "volRatio": 1.0353
     },
     {
      "n": 19083,
      "dwell": 0.9421,
      "nextRangeAtr": 0.089,
      "volRatio": 0.9698
     },
     {
      "n": 19080,
      "dwell": 0.8858,
      "nextRangeAtr": 0.119,
      "volRatio": 0.8567
     }
    ],
    "medianNextRangeAtr": 0.0866
   },
   "london": {
    "n": 76426,
    "cuts": [
     0.0006,
     0.0013,
     0.0022,
     0.0036
    ],
    "quintiles": [
     {
      "n": 15286,
      "dwell": 0.909,
      "nextRangeAtr": 0.1144,
      "volRatio": 1.0915
     },
     {
      "n": 15285,
      "dwell": 0.9051,
      "nextRangeAtr": 0.117,
      "volRatio": 1.0908
     },
     {
      "n": 15285,
      "dwell": 0.8968,
      "nextRangeAtr": 0.1206,
      "volRatio": 1.051
     },
     {
      "n": 15285,
      "dwell": 0.8812,
      "nextRangeAtr": 0.1295,
      "volRatio": 0.9939
     },
     {
      "n": 15285,
      "dwell": 0.8243,
      "nextRangeAtr": 0.1563,
      "volRatio": 0.8624
     }
    ],
    "medianNextRangeAtr": 0.1266
   },
   "ny": {
    "n": 76370,
    "cuts": [
     0.0011,
     0.0024,
     0.0042,
     0.0074
    ],
    "quintiles": [
     {
      "n": 15274,
      "dwell": 0.7193,
      "nextRangeAtr": 0.2247,
      "volRatio": 1.2099
     },
     {
      "n": 15274,
      "dwell": 0.6999,
      "nextRangeAtr": 0.2345,
      "volRatio": 1.1806
     },
     {
      "n": 15274,
      "dwell": 0.6751,
      "nextRangeAtr": 0.2524,
      "volRatio": 1.0877
     },
     {
      "n": 15274,
      "dwell": 0.6232,
      "nextRangeAtr": 0.2772,
      "volRatio": 0.9599
     },
     {
      "n": 15274,
      "dwell": 0.5281,
      "nextRangeAtr": 0.3397,
      "volRatio": 0.8263
     }
    ],
    "medianNextRangeAtr": 0.2684
   },
   "late": {
    "n": 61560,
    "cuts": [
     0.0009,
     0.002,
     0.0035,
     0.0061
    ],
    "quintiles": [
     {
      "n": 12312,
      "dwell": 0.8214,
      "nextRangeAtr": 0.149,
      "volRatio": 0.8759
     },
     {
      "n": 12312,
      "dwell": 0.7958,
      "nextRangeAtr": 0.1645,
      "volRatio": 0.9035
     },
     {
      "n": 12312,
      "dwell": 0.7631,
      "nextRangeAtr": 0.1846,
      "volRatio": 0.9173
     },
     {
      "n": 12312,
      "dwell": 0.7168,
      "nextRangeAtr": 0.2065,
      "volRatio": 0.8957
     },
     {
      "n": 12312,
      "dwell": 0.6272,
      "nextRangeAtr": 0.2606,
      "volRatio": 0.796
     }
    ],
    "medianNextRangeAtr": 0.1918
   }
  }
 },
 "spx": {
  "pair": "spx",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-06-05",
   "sessions": 1223
  },
  "bands": {
   "asia": {
    "n": 85968,
    "cuts": [
     0.0004,
     0.0009,
     0.0015,
     0.0026
    ],
    "quintiles": [
     {
      "n": 17194,
      "dwell": 0.9612,
      "nextRangeAtr": 0.077,
      "volRatio": 1.087
     },
     {
      "n": 17193,
      "dwell": 0.9543,
      "nextRangeAtr": 0.0798,
      "volRatio": 1.0731
     },
     {
      "n": 17195,
      "dwell": 0.9511,
      "nextRangeAtr": 0.0836,
      "volRatio": 1.0462
     },
     {
      "n": 17192,
      "dwell": 0.9381,
      "nextRangeAtr": 0.0921,
      "volRatio": 1
     },
     {
      "n": 17194,
      "dwell": 0.8797,
      "nextRangeAtr": 0.1203,
      "volRatio": 0.8692
     }
    ],
    "medianNextRangeAtr": 0.0889
   },
   "london": {
    "n": 72508,
    "cuts": [
     0.0006,
     0.0014,
     0.0023,
     0.0038
    ],
    "quintiles": [
     {
      "n": 14502,
      "dwell": 0.9003,
      "nextRangeAtr": 0.1177,
      "volRatio": 1.0953
     },
     {
      "n": 14501,
      "dwell": 0.8958,
      "nextRangeAtr": 0.118,
      "volRatio": 1.0794
     },
     {
      "n": 14503,
      "dwell": 0.8875,
      "nextRangeAtr": 0.1239,
      "volRatio": 1.0601
     },
     {
      "n": 14501,
      "dwell": 0.8673,
      "nextRangeAtr": 0.1345,
      "volRatio": 0.987
     },
     {
      "n": 14501,
      "dwell": 0.7967,
      "nextRangeAtr": 0.1666,
      "volRatio": 0.8696
     }
    ],
    "medianNextRangeAtr": 0.1309
   },
   "ny": {
    "n": 72853,
    "cuts": [
     0.0011,
     0.0024,
     0.0041,
     0.0072
    ],
    "quintiles": [
     {
      "n": 14571,
      "dwell": 0.7215,
      "nextRangeAtr": 0.2148,
      "volRatio": 1.2027
     },
     {
      "n": 14571,
      "dwell": 0.7105,
      "nextRangeAtr": 0.2237,
      "volRatio": 1.1643
     },
     {
      "n": 14570,
      "dwell": 0.6808,
      "nextRangeAtr": 0.239,
      "volRatio": 1.0962
     },
     {
      "n": 14570,
      "dwell": 0.6363,
      "nextRangeAtr": 0.2648,
      "volRatio": 0.9948
     },
     {
      "n": 14571,
      "dwell": 0.5368,
      "nextRangeAtr": 0.3329,
      "volRatio": 0.8506
     }
    ],
    "medianNextRangeAtr": 0.2546
   },
   "late": {
    "n": 57238,
    "cuts": [
     0.001,
     0.0022,
     0.0038,
     0.0066
    ],
    "quintiles": [
     {
      "n": 11448,
      "dwell": 0.7869,
      "nextRangeAtr": 0.168,
      "volRatio": 0.922
     },
     {
      "n": 11447,
      "dwell": 0.764,
      "nextRangeAtr": 0.1807,
      "volRatio": 0.9381
     },
     {
      "n": 11450,
      "dwell": 0.7353,
      "nextRangeAtr": 0.1984,
      "volRatio": 0.9461
     },
     {
      "n": 11445,
      "dwell": 0.692,
      "nextRangeAtr": 0.2221,
      "volRatio": 0.9115
     },
     {
      "n": 11448,
      "dwell": 0.5905,
      "nextRangeAtr": 0.2891,
      "volRatio": 0.8056
     }
    ],
    "medianNextRangeAtr": 0.2085
   }
  }
 },
 "dow": {
  "pair": "dow",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-06-05",
   "sessions": 1223
  },
  "bands": {
   "asia": {
    "n": 89263,
    "cuts": [
     0.0004,
     0.0008,
     0.0013,
     0.0023
    ],
    "quintiles": [
     {
      "n": 17853,
      "dwell": 0.9719,
      "nextRangeAtr": 0.0674,
      "volRatio": 1.0938
     },
     {
      "n": 17852,
      "dwell": 0.9672,
      "nextRangeAtr": 0.0698,
      "volRatio": 1.0714
     },
     {
      "n": 17854,
      "dwell": 0.9628,
      "nextRangeAtr": 0.0739,
      "volRatio": 1.0422
     },
     {
      "n": 17851,
      "dwell": 0.9522,
      "nextRangeAtr": 0.0828,
      "volRatio": 1
     },
     {
      "n": 17853,
      "dwell": 0.9022,
      "nextRangeAtr": 0.1097,
      "volRatio": 0.8784
     }
    ],
    "medianNextRangeAtr": 0.0791
   },
   "london": {
    "n": 73024,
    "cuts": [
     0.0006,
     0.0013,
     0.0022,
     0.0037
    ],
    "quintiles": [
     {
      "n": 14606,
      "dwell": 0.9021,
      "nextRangeAtr": 0.1151,
      "volRatio": 1.1041
     },
     {
      "n": 14604,
      "dwell": 0.9009,
      "nextRangeAtr": 0.1169,
      "volRatio": 1.0849
     },
     {
      "n": 14604,
      "dwell": 0.8933,
      "nextRangeAtr": 0.1221,
      "volRatio": 1.0556
     },
     {
      "n": 14606,
      "dwell": 0.8747,
      "nextRangeAtr": 0.1313,
      "volRatio": 0.9894
     },
     {
      "n": 14604,
      "dwell": 0.8064,
      "nextRangeAtr": 0.1612,
      "volRatio": 0.8553
     }
    ],
    "medianNextRangeAtr": 0.1285
   },
   "ny": {
    "n": 73064,
    "cuts": [
     0.0011,
     0.0024,
     0.0043,
     0.0075
    ],
    "quintiles": [
     {
      "n": 14613,
      "dwell": 0.7118,
      "nextRangeAtr": 0.2311,
      "volRatio": 1.2474
     },
     {
      "n": 14613,
      "dwell": 0.6949,
      "nextRangeAtr": 0.239,
      "volRatio": 1.1886
     },
     {
      "n": 14612,
      "dwell": 0.6657,
      "nextRangeAtr": 0.2582,
      "volRatio": 1.0942
     },
     {
      "n": 14614,
      "dwell": 0.6253,
      "nextRangeAtr": 0.2785,
      "volRatio": 0.9606
     },
     {
      "n": 14612,
      "dwell": 0.5277,
      "nextRangeAtr": 0.3403,
      "volRatio": 0.8255
     }
    ],
    "medianNextRangeAtr": 0.2712
   },
   "late": {
    "n": 58782,
    "cuts": [
     0.001,
     0.0022,
     0.0037,
     0.0064
    ],
    "quintiles": [
     {
      "n": 11758,
      "dwell": 0.7985,
      "nextRangeAtr": 0.1629,
      "volRatio": 0.8622
     },
     {
      "n": 11755,
      "dwell": 0.7801,
      "nextRangeAtr": 0.1766,
      "volRatio": 0.9014
     },
     {
      "n": 11756,
      "dwell": 0.7461,
      "nextRangeAtr": 0.1945,
      "volRatio": 0.917
     },
     {
      "n": 11756,
      "dwell": 0.7075,
      "nextRangeAtr": 0.215,
      "volRatio": 0.9013
     },
     {
      "n": 11757,
      "dwell": 0.6139,
      "nextRangeAtr": 0.2731,
      "volRatio": 0.7974
     }
    ],
    "medianNextRangeAtr": 0.2022
   }
  }
 },
 "us2000": {
  "pair": "us2000",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1277
  },
  "bands": {
   "asia": {
    "n": 88420,
    "cuts": [
     0.0004,
     0.0008,
     0.0014,
     0.0024
    ],
    "quintiles": [
     {
      "n": 17684,
      "dwell": 0.9675,
      "nextRangeAtr": 0.0715,
      "volRatio": 1.0824
     },
     {
      "n": 17686,
      "dwell": 0.9643,
      "nextRangeAtr": 0.0729,
      "volRatio": 1.0698
     },
     {
      "n": 17682,
      "dwell": 0.9612,
      "nextRangeAtr": 0.0772,
      "volRatio": 1.0472
     },
     {
      "n": 17684,
      "dwell": 0.9508,
      "nextRangeAtr": 0.085,
      "volRatio": 1
     },
     {
      "n": 17684,
      "dwell": 0.8986,
      "nextRangeAtr": 0.1106,
      "volRatio": 0.875
     }
    ],
    "medianNextRangeAtr": 0.0821
   },
   "london": {
    "n": 75135,
    "cuts": [
     0.0006,
     0.0014,
     0.0023,
     0.0037
    ],
    "quintiles": [
     {
      "n": 15027,
      "dwell": 0.9033,
      "nextRangeAtr": 0.1174,
      "volRatio": 1.1185
     },
     {
      "n": 15027,
      "dwell": 0.8996,
      "nextRangeAtr": 0.1192,
      "volRatio": 1.1042
     },
     {
      "n": 15028,
      "dwell": 0.8925,
      "nextRangeAtr": 0.1237,
      "volRatio": 1.0623
     },
     {
      "n": 15027,
      "dwell": 0.8746,
      "nextRangeAtr": 0.1318,
      "volRatio": 1
     },
     {
      "n": 15026,
      "dwell": 0.8144,
      "nextRangeAtr": 0.1566,
      "volRatio": 0.8846
     }
    ],
    "medianNextRangeAtr": 0.1289
   },
   "ny": {
    "n": 76038,
    "cuts": [
     0.0012,
     0.0026,
     0.0045,
     0.0078
    ],
    "quintiles": [
     {
      "n": 15208,
      "dwell": 0.6994,
      "nextRangeAtr": 0.2367,
      "volRatio": 1.2366
     },
     {
      "n": 15207,
      "dwell": 0.6826,
      "nextRangeAtr": 0.2454,
      "volRatio": 1.1607
     },
     {
      "n": 15208,
      "dwell": 0.6565,
      "nextRangeAtr": 0.2609,
      "volRatio": 1.0597
     },
     {
      "n": 15207,
      "dwell": 0.6163,
      "nextRangeAtr": 0.2781,
      "volRatio": 0.917
     },
     {
      "n": 15208,
      "dwell": 0.5127,
      "nextRangeAtr": 0.3478,
      "volRatio": 0.797
     }
    ],
    "medianNextRangeAtr": 0.2753
   },
   "late": {
    "n": 59863,
    "cuts": [
     0.0009,
     0.002,
     0.0035,
     0.0058
    ],
    "quintiles": [
     {
      "n": 11973,
      "dwell": 0.8221,
      "nextRangeAtr": 0.1505,
      "volRatio": 0.8833
     },
     {
      "n": 11972,
      "dwell": 0.8105,
      "nextRangeAtr": 0.1581,
      "volRatio": 0.8867
     },
     {
      "n": 11973,
      "dwell": 0.7859,
      "nextRangeAtr": 0.1713,
      "volRatio": 0.8955
     },
     {
      "n": 11972,
      "dwell": 0.7468,
      "nextRangeAtr": 0.1898,
      "volRatio": 0.8841
     },
     {
      "n": 11973,
      "dwell": 0.652,
      "nextRangeAtr": 0.2409,
      "volRatio": 0.7902
     }
    ],
    "medianNextRangeAtr": 0.1799
   }
  }
 },
 "de30": {
  "pair": "de30",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1259
  },
  "bands": {
   "asia": {
    "n": 78398,
    "cuts": [
     0.0006,
     0.0012,
     0.002,
     0.0034
    ],
    "quintiles": [
     {
      "n": 15682,
      "dwell": 0.9044,
      "nextRangeAtr": 0.1037,
      "volRatio": 1.1862
     },
     {
      "n": 15677,
      "dwell": 0.8977,
      "nextRangeAtr": 0.1075,
      "volRatio": 1.1818
     },
     {
      "n": 15680,
      "dwell": 0.8869,
      "nextRangeAtr": 0.1144,
      "volRatio": 1.15
     },
     {
      "n": 15679,
      "dwell": 0.8634,
      "nextRangeAtr": 0.1278,
      "volRatio": 1.0927
     },
     {
      "n": 15680,
      "dwell": 0.7762,
      "nextRangeAtr": 0.1825,
      "volRatio": 1.04
     }
    ],
    "medianNextRangeAtr": 0.1232
   },
   "london": {
    "n": 75452,
    "cuts": [
     0.0012,
     0.0025,
     0.0042,
     0.0068
    ],
    "quintiles": [
     {
      "n": 15091,
      "dwell": 0.7405,
      "nextRangeAtr": 0.2022,
      "volRatio": 1
     },
     {
      "n": 15091,
      "dwell": 0.7307,
      "nextRangeAtr": 0.2061,
      "volRatio": 0.9895
     },
     {
      "n": 15089,
      "dwell": 0.7144,
      "nextRangeAtr": 0.2136,
      "volRatio": 0.962
     },
     {
      "n": 15090,
      "dwell": 0.6872,
      "nextRangeAtr": 0.2283,
      "volRatio": 0.9055
     },
     {
      "n": 15091,
      "dwell": 0.6032,
      "nextRangeAtr": 0.2765,
      "volRatio": 0.8112
     }
    ],
    "medianNextRangeAtr": 0.224
   },
   "ny": {
    "n": 75490,
    "cuts": [
     0.0011,
     0.0024,
     0.0039,
     0.0065
    ],
    "quintiles": [
     {
      "n": 15099,
      "dwell": 0.7538,
      "nextRangeAtr": 0.1913,
      "volRatio": 1.0072
     },
     {
      "n": 15097,
      "dwell": 0.75,
      "nextRangeAtr": 0.1951,
      "volRatio": 0.9855
     },
     {
      "n": 15098,
      "dwell": 0.7282,
      "nextRangeAtr": 0.2067,
      "volRatio": 0.9566
     },
     {
      "n": 15098,
      "dwell": 0.6971,
      "nextRangeAtr": 0.2267,
      "volRatio": 0.9252
     },
     {
      "n": 15098,
      "dwell": 0.6112,
      "nextRangeAtr": 0.2751,
      "volRatio": 0.8208
     }
    ],
    "medianNextRangeAtr": 0.2183
   },
   "late": {
    "n": 35776,
    "cuts": [
     0.0007,
     0.0015,
     0.0025,
     0.0042
    ],
    "quintiles": [
     {
      "n": 7156,
      "dwell": 0.8962,
      "nextRangeAtr": 0.116,
      "volRatio": 0.9792
     },
     {
      "n": 7155,
      "dwell": 0.8874,
      "nextRangeAtr": 0.1208,
      "volRatio": 0.9545
     },
     {
      "n": 7155,
      "dwell": 0.8772,
      "nextRangeAtr": 0.1276,
      "volRatio": 0.9421
     },
     {
      "n": 7155,
      "dwell": 0.8464,
      "nextRangeAtr": 0.1431,
      "volRatio": 0.8917
     },
     {
      "n": 7155,
      "dwell": 0.7446,
      "nextRangeAtr": 0.1908,
      "volRatio": 0.8052
     }
    ],
    "medianNextRangeAtr": 0.1371
   }
  }
 },
 "uk100": {
  "pair": "uk100",
  "coverage": {
   "from": "2021-09-13",
   "to": "2026-08-20",
   "sessions": 1246
  },
  "bands": {
   "asia": {
    "n": 70728,
    "cuts": [
     0.0006,
     0.0012,
     0.0021,
     0.0035
    ],
    "quintiles": [
     {
      "n": 14146,
      "dwell": 0.8966,
      "nextRangeAtr": 0.1087,
      "volRatio": 1.1687
     },
     {
      "n": 14145,
      "dwell": 0.8933,
      "nextRangeAtr": 0.1121,
      "volRatio": 1.1714
     },
     {
      "n": 14146,
      "dwell": 0.8786,
      "nextRangeAtr": 0.1179,
      "volRatio": 1.149
     },
     {
      "n": 14145,
      "dwell": 0.8548,
      "nextRangeAtr": 0.132,
      "volRatio": 1.1048
     },
     {
      "n": 14146,
      "dwell": 0.7635,
      "nextRangeAtr": 0.1853,
      "volRatio": 1.051
     }
    ],
    "medianNextRangeAtr": 0.1269
   },
   "london": {
    "n": 74557,
    "cuts": [
     0.0012,
     0.0025,
     0.0042,
     0.0069
    ],
    "quintiles": [
     {
      "n": 14912,
      "dwell": 0.7374,
      "nextRangeAtr": 0.1999,
      "volRatio": 1
     },
     {
      "n": 14911,
      "dwell": 0.7248,
      "nextRangeAtr": 0.2057,
      "volRatio": 0.9895
     },
     {
      "n": 14911,
      "dwell": 0.7156,
      "nextRangeAtr": 0.2123,
      "volRatio": 0.9494
     },
     {
      "n": 14911,
      "dwell": 0.6817,
      "nextRangeAtr": 0.2266,
      "volRatio": 0.9024
     },
     {
      "n": 14912,
      "dwell": 0.5946,
      "nextRangeAtr": 0.2781,
      "volRatio": 0.8
     }
    ],
    "medianNextRangeAtr": 0.2231
   },
   "ny": {
    "n": 74035,
    "cuts": [
     0.0012,
     0.0025,
     0.0042,
     0.0068
    ],
    "quintiles": [
     {
      "n": 14808,
      "dwell": 0.7253,
      "nextRangeAtr": 0.2039,
      "volRatio": 1.0268
     },
     {
      "n": 14806,
      "dwell": 0.7198,
      "nextRangeAtr": 0.2098,
      "volRatio": 1.0186
     },
     {
      "n": 14807,
      "dwell": 0.7052,
      "nextRangeAtr": 0.2188,
      "volRatio": 0.9867
     },
     {
      "n": 14808,
      "dwell": 0.6743,
      "nextRangeAtr": 0.2363,
      "volRatio": 0.9468
     },
     {
      "n": 14806,
      "dwell": 0.6004,
      "nextRangeAtr": 0.2805,
      "volRatio": 0.8515
     }
    ],
    "medianNextRangeAtr": 0.2297
   },
   "late": {
    "n": 34435,
    "cuts": [
     0.0008,
     0.0017,
     0.0027,
     0.0045
    ],
    "quintiles": [
     {
      "n": 6887,
      "dwell": 0.8694,
      "nextRangeAtr": 0.129,
      "volRatio": 0.9774
     },
     {
      "n": 6888,
      "dwell": 0.8663,
      "nextRangeAtr": 0.1311,
      "volRatio": 0.9652
     },
     {
      "n": 6887,
      "dwell": 0.8571,
      "nextRangeAtr": 0.1362,
      "volRatio": 0.9472
     },
     {
      "n": 6886,
      "dwell": 0.8202,
      "nextRangeAtr": 0.1506,
      "volRatio": 0.9112
     },
     {
      "n": 6887,
      "dwell": 0.7248,
      "nextRangeAtr": 0.1979,
      "volRatio": 0.8249
     }
    ],
    "medianNextRangeAtr": 0.1455
   }
  }
 }
};
