/**
 * js/tapeSpeedEngine.js — how fast is the tape moving right now, and what kind of
 * hour has that pace historically produced?
 *
 * Pure. Reads the frozen table in js/tapeSpeedParams.js (generated by
 * analysis/build_tape_speed_params.mjs); the caller supplies the live inputs.
 *
 * The measure is 15-minute speed in ATR per minute, cut into quintiles WITHIN the
 * current session band -- the fastest fifth in the NY overlap starts at roughly
 * double the speed it does in Asia, so a single full-day cut would mislabel most
 * arrivals at both ends of the day.
 *
 * What it says and does not say. The table records, for each speed quintile, the
 * share of the next hour price stayed within 0.10 ATR of where it was (dwell), the
 * median next-hour range, and that range relative to the previous hour. Speed
 * persists: a slow tape tends to stay slow for an hour, a fast one to stay fast.
 * That is a statement about the next hour's RANGE, not its direction, and it is
 * unconditional on levels -- analysis/approach_speed_control_study.mjs showed the
 * effect is the same at random non-level prices as at real ones, so it belongs to
 * every bar rather than to the moments price meets a line.
 */
import { TAPE_SPEED_PARAMS } from './tapeSpeedParams.js';

export const SPEED_BARS = 15;
export const LABELS = ['DRIFT', 'slow', 'mid', 'quick', 'FAST'];

export const bandOf = h => (h >= 23 || h < 7) ? 'asia' : h < 12 ? 'london' : h < 17 ? 'ny' : 'late';
export const BAND_LABEL = { asia: 'Asia 23:00-07:00', london: 'London 07:00-12:00', ny: 'NY overlap 12:00-17:00', late: 'Late 17:00-23:00' };

/** Which params key an OANDA-style symbol maps to. */
export function paramsKeyFor(symbol) {
  const s = String(symbol || '').toUpperCase().replace('/', '_');
  const MAP = { XAU_USD: 'gold', NAS100_USD: 'nq', SPX500_USD: 'spx', US30_USD: 'dow', US2000_USD: 'us2000', DE30_EUR: 'de30', UK100_GBP: 'uk100' };
  if (MAP[s]) return MAP[s];
  const fx = s.replace('_', '').toLowerCase();
  return fx.length === 6 ? fx : null;
}

/** Daily ATR(14) from daily bars [{high, low, close}] oldest -> newest. */
export function atr14(dailyBars, n = 14) {
  if (!Array.isArray(dailyBars) || dailyBars.length < n + 1) return null;
  const b = dailyBars.slice(-(n + 1));
  let s = 0;
  for (let i = 1; i < b.length; i++) {
    const c = b[i], p = b[i - 1];
    s += Math.max(c.high - c.low, Math.abs(c.high - p.close), Math.abs(c.low - p.close));
  }
  return s / n;
}

/**
 * 15-minute speed from M1 closes (oldest -> newest), in ATR per minute.
 * Uses the last COMPLETED bars: closes[-1] is the most recent close.
 */
export function speedFromCloses(closes, atr, bars = SPEED_BARS) {
  if (!Array.isArray(closes) || closes.length < bars + 1 || !(atr > 0)) return null;
  const to = closes[closes.length - 1], from = closes[closes.length - 1 - bars];
  if (!Number.isFinite(to) || !Number.isFinite(from)) return null;
  return { speed: Math.abs(to - from) / bars / atr, signed: (to - from) / bars / atr, move: to - from };
}

/**
 * Classify a speed against this instrument's own history in this band.
 * Returns null, never a guess, when the instrument or band has no table.
 */
export function classifyTapeSpeed(symbol, hourUtc, speed, params = TAPE_SPEED_PARAMS) {
  const key = paramsKeyFor(symbol);
  const p = key ? params[key] : null;
  const band = bandOf(hourUtc);
  const b = p?.bands?.[band];
  if (!b || !Number.isFinite(speed)) return null;
  let q = 0; while (q < 4 && speed > b.cuts[q]) q++;
  const row = b.quintiles[q];
  // Percentile of this speed among the band's history, from the cut points: a
  // coarse but honest "faster than ~x% of the time" without shipping the raw sample.
  const pctile = q === 0 ? '<p20' : q === 4 ? '>p80' : `p${q * 20}-${(q + 1) * 20}`;
  return {
    key, band, bandLabel: BAND_LABEL[band],
    quintile: q + 1, label: LABELS[q], pctile,
    speed, cuts: b.cuts,
    dwell: row.dwell, nextRangeAtr: row.nextRangeAtr, volRatio: row.volRatio, n: row.n,
    bandMedianNextRangeAtr: b.medianNextRangeAtr,
    // How this quintile's typical next hour compares with the band's typical hour.
    nextRangeVsTypical: (row.nextRangeAtr != null && b.medianNextRangeAtr > 0) ? +(row.nextRangeAtr / b.medianNextRangeAtr).toFixed(2) : null,
    coverage: p.coverage,
  };
}

/** One-line plain-English read of a classification, for the card and the prompt. */
export function describeTapeSpeed(c) {
  if (!c) return null;
  const vsTyp = c.nextRangeVsTypical;
  const rangeWord = vsTyp == null ? '' : vsTyp >= 1.15 ? 'wider than a typical hour' : vsTyp <= 0.87 ? 'narrower than a typical hour' : 'about a typical hour';
  const lastWord = c.volRatio == null ? '' : c.volRatio >= 1.05 ? 'and a little wider than the last hour' : c.volRatio <= 0.9 ? 'but calmer than the hour just gone' : 'and much like the last hour';
  return `Tape is ${c.label} (${c.pctile} for ${c.bandLabel}). At this pace the next hour has historically stayed within 0.1 ATR of here ${Math.round(c.dwell * 100)}% of the time, with a range ${rangeWord}${lastWord ? ' ' + lastWord : ''} (median ${c.nextRangeAtr} ATR, n=${c.n.toLocaleString()}).`;
}
