"""q47.py - does VWAP extension transfer to an INDEPENDENT strategy's trades?

THE POPULATION-MISMATCH PROBLEM THIS EXISTS TO SETTLE
-----------------------------------------------------
The adverse-excursion result (4.80 -> 2.80 ATR as extension rises) was measured
on extension events themselves - the event WAS the extension. Applying it to
trades generated by an unrelated strategy that merely happen to occur at an
extended moment is a DIFFERENT POPULATION, and the relationship may not carry.
Assuming it does would be the same error as every other false start in this
programme.

So this runs in two stages and stops early if stage 1 fails.

  STAGE 1  At an independent strategy's entries, does VWAP extension predict
           the subsequent MAE distribution? Median / p75 / p90 / p95, in ATR.
           If not, extension is archived as descriptive and nothing else runs.

  STAGE 2  Only if stage 1 passes: does using that information improve the
           strategy's net risk-adjusted performance out of sample?

THE CONTROL STRATEGY
  The Vol Forecast fade: limit at open +/- HL_75 (EWMA vol forecast from data to
  T-1), resolved on the real M1 path. Its entry logic contains no VWAP, no ATR
  and no oscillator, so it is genuinely independent of the variable being tested.

THE SHUFFLE CONTROL
  Extension values are permuted WITHIN (instrument x NY-hour x volatility
  tercile) cells and the whole analysis re-run. If the real overlay does not
  beat the shuffled one, any apparent effect is a property of the trade
  population rather than information transferred from extension.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

EWMA_LAMBDA = 0.94
BM_RANGE_P75 = 2.049
CORR = {'fx': 0.894, 'commodity': 0.989, 'index': 0.950}
ASSET = {'xauusd': 'commodity', 'nq': 'index', 'spx500': 'index', 'us30': 'index',
         'de30': 'index', 'uk100': 'index'}
SL_MULT = 1.5
MIN_LOOKBACK = 50


def _ewma_var(lr, lam=EWMA_LAMBDA):
    v = float(np.var(lr[:min(20, len(lr))])) or 1e-10
    for r in lr:
        v = lam * v + (1.0 - lam) * r * r
    return v


def _atr(h, l, c, n=60):
    pc = np.concatenate([[c[0]], c[:-1]])
    tr = np.maximum(h - l, np.maximum(np.abs(h - pc), np.abs(l - pc)))
    return pd.Series(tr).ewm(alpha=1.0 / n, adjust=False).mean().to_numpy()


def _ext(h, l, c, v, a, window=60):
    tp = (h + l + c) / 3.0
    vv = np.ones_like(tp) if v is None else v
    num = pd.Series(tp * vv).rolling(window, min_periods=window // 4).sum().to_numpy()
    den = pd.Series(vv).rolling(window, min_periods=window // 4).sum().to_numpy()
    with np.errstate(divide='ignore', invalid='ignore'):
        vw = np.where(den > 0, num / den, np.nan)
        return (c - vw) / a


def generate_trades(inst, m1):
    """The independent strategy's fills, with context recorded at entry.

    Entry logic uses ONLY the prior daily closes and today's open. No VWAP, no
    ATR, no oscillator - so extension is genuinely exogenous to the signal.
    """
    ac = ASSET.get(inst, 'fx')
    d1 = m1.resample('1D').agg({'open': 'first', 'high': 'max',
                                'low': 'min', 'close': 'last'}).dropna()
    closes = d1['close'].to_numpy(float)
    opens = d1['open'].to_numpy(float)
    days = d1.index

    h = m1['high'].to_numpy(float)
    l = m1['low'].to_numpy(float)
    c = m1['close'].to_numpy(float)
    v = m1['volume'].to_numpy(float) if 'volume' in m1.columns else None
    a = _atr(h, l, c)
    ext = _ext(h, l, c, v, a)
    ny = m1.index.tz_convert('America/New_York').hour.to_numpy()
    volrank = pd.Series(a / c).rolling(20000, min_periods=2000).rank(pct=True).to_numpy()

    day_of = m1.index.normalize()
    starts = np.searchsorted(day_of, days, side='left')
    ends = np.searchsorted(day_of, days, side='right')

    rows = []
    for i in range(MIN_LOOKBACK, len(d1)):
        lr = np.log(closes[1:i] / closes[:i - 1])
        if len(lr) < 20:
            continue
        sigma_d = np.sqrt(_ewma_var(lr))
        o = opens[i]
        hl_d = o * (BM_RANGE_P75 * CORR[ac] * sigma_d * 100.0) / 100.0
        if not np.isfinite(hl_d) or hl_d <= 0:
            continue
        s, e = starts[i], ends[i]
        if e - s < 30:
            continue
        dh, dl = h[s:e], l[s:e]
        up = np.where(dh >= o + hl_d)[0]
        dn = np.where(dl <= o - hl_d)[0]
        fu = up[0] if up.size else 10**9
        fd = dn[0] if dn.size else 10**9
        if fu == fd:
            continue
        if fu < fd:
            side, entry_px, k = -1, o + hl_d, fu       # SELL the upper extreme
            tp, stp = o, o + hl_d * SL_MULT
        else:
            side, entry_px, k = 1, o - hl_d, fd        # BUY the lower extreme
            tp, stp = o, o - hl_d * SL_MULT
        gi = s + k
        if not np.isfinite(a[gi]) or a[gi] <= 0 or not np.isfinite(ext[gi]):
            continue

        fh, fl = dh[k + 1:], dl[k + 1:]
        if fh.size < 5:
            continue
        # Outcome on the real path, in true order.
        if side < 0:
            t_tp = np.where(fl <= tp)[0]
            t_sl = np.where(fh >= stp)[0]
            mae = (np.maximum.accumulate(fh) - entry_px).max() / a[gi]
            mfe = (entry_px - np.minimum.accumulate(fl)).max() / a[gi]
        else:
            t_tp = np.where(fh >= tp)[0]
            t_sl = np.where(fl <= stp)[0]
            mae = (entry_px - np.minimum.accumulate(fl)).max() / a[gi]
            mfe = (np.maximum.accumulate(fh) - entry_px).max() / a[gi]
        A = t_tp[0] if t_tp.size else 10**9
        B = t_sl[0] if t_sl.size else 10**9
        if A == B == 10**9:
            pnl = (entry_px - c[s + e - s - 1]) * side / a[gi] * -1 if False else \
                  (c[e - 1] - entry_px) * side / a[gi]
            outcome = 'open'
        elif A < B:
            pnl = abs(entry_px - tp) / a[gi]
            outcome = 'win'
        else:
            pnl = -abs(stp - entry_px) / a[gi]
            outcome = 'loss'

        rows.append({
            'instrument': inst, 'time': m1.index[gi], 'side': side,
            # SIGNED so positive = price extended in the direction we are fading.
            'ext_signed': float(ext[gi]) * -side,
            'ext_abs': abs(float(ext[gi])),
            'atr': float(a[gi]), 'ny_hour': int(ny[gi]),
            'vol_rank': float(volrank[gi]) if np.isfinite(volrank[gi]) else np.nan,
            'mae_atr': float(mae), 'mfe_atr': float(mfe),
            'pnl_atr': float(pnl), 'outcome': outcome,
            'stopped': 1.0 if outcome == 'loss' else 0.0,
        })
    return pd.DataFrame(rows)


def stage1(t, col='ext_signed', label='REAL'):
    """Does extension predict the MAE distribution at these independent entries?"""
    d = t[np.isfinite(t[col]) & np.isfinite(t['mae_atr'])].copy()
    q = pd.qcut(d[col], 5, labels=False, duplicates='drop')
    out = []
    for k in range(int(q.max()) + 1):
        g = d[q == k]
        out.append({'bucket': k + 1, 'n': len(g), 'ext': g[col].median(),
                    'mae_med': g.mae_atr.median(), 'mae_p75': g.mae_atr.quantile(0.75),
                    'mae_p90': g.mae_atr.quantile(0.90), 'mae_p95': g.mae_atr.quantile(0.95),
                    'stopout': g.stopped.mean(), 'mfe_med': g.mfe_atr.median()})
    r = pd.DataFrame(out)
    r['label'] = label
    return r


def shuffle_within(t, seed=0):
    """Permute extension inside (instrument x NY hour x vol tercile) cells."""
    rng = np.random.default_rng(seed)
    d = t.copy()
    vt = pd.qcut(d.vol_rank.rank(method='first'), 3, labels=False, duplicates='drop')
    key = d.instrument.astype(str) + '_' + d.ny_hour.astype(str) + '_' + pd.Series(vt, index=d.index).astype(str)
    out = d.ext_signed.to_numpy().copy()
    for _, idx in d.groupby(key).groups.items():
        pos = d.index.get_indexer(idx)
        out[pos] = rng.permutation(out[pos])
    d['ext_shuffled'] = out
    return d
