"""Freeze the S1 shadow params (forge/VF3_SHADOW_P1_PREREG.md): P1 tables refit on all history through 2026-08-20 and a fixed
logit level correction delta per endpoint estimated on 2025-08-21..2026-08-20. Writes js/intradayProbShadowParams.js.
    PYTHONPATH=. python scripts/forecast_history/export_ips_shadow_params.py"""
import hashlib, json
from pathlib import Path
import numpy as np, pandas as pd
import vf3_stage_c_p1 as P

P.FIT_END = "2026-08-21"                                  # every row through 2026-08-20 is 'fit'
DELTA_FROM, DELTA_TO = "2025-08-21", "2026-08-21"


def delta(p, y):
    lg = np.log(np.clip(p, 1e-4, 1 - 1e-4) / (1 - np.clip(p, 1e-4, 1 - 1e-4)))
    d = 0.0
    for _ in range(50):
        q = 1 / (1 + np.exp(-(lg + d)))
        g, h = np.sum(q - y), np.sum(q * (1 - q))
        d -= g / max(h, 1e-9)
    return float(d)


X = P.load()
oos = P.node_json("import('./js/forecastLadderParams.js').then(m=>console.log(JSON.stringify(Object.fromEntries(Object.entries(m.LADDER_PARAMS.pairs).map(([k,v])=>[k,v.oos_exceed])))))")
T1, t1 = P.t1_rows(X, oos)
C = pd.read_parquet("analysis/output/vf3_stage_b/part1_lines.parquet", columns=["inst", "date", "C_hl_p50"])
Gb, tb = P.t2_rows(X, C, "L_B")
Ga, ta = P.t2_rows(X, C, "L_A")
out = {"registered": "forge/VF3_SHADOW_P1_PREREG.md", "fit_through": "2026-08-20", "delta_window": [DELTA_FROM, "2026-08-20"], "m": P.M,
       "T1": {"clim": t1["clim"], "table": t1["table"]}, "T2_L_B": tb, "T2_L_A": ta, "delta": {}, "fit_rows": {}}
for k, D in (("T1", T1), ("T2_L_B", Gb), ("T2_L_A", Ga)):
    w = D[(D.date >= DELTA_FROM) & (D.date < DELTA_TO) & (D.oos == 1)]
    out["delta"][k] = round(delta(w.chal.to_numpy(), w.y.to_numpy()), 5)
    out["fit_rows"][k] = {"table_rows": int((D.block == "fit").sum()), "delta_rows": int(len(w)), "delta_window_realised": round(float(w.y.mean()), 4), "delta_window_table_mean": round(float(w.chal.mean()), 4)}
body = json.dumps(out, default=float, separators=(",", ":"))
ver = hashlib.sha256(body.encode()).hexdigest()
js = ("// GENERATED by scripts/forecast_history/export_ips_shadow_params.py - do not hand-edit.\n"
      "// S1 shadow (forge/VF3_SHADOW_P1_PREREG.md): frozen intraday probability tables + fixed level correction. Read-only shadow; nothing live reads this.\n"
      f"export const IPS_MODEL_VERSION = '{ver}';\nexport const IPS_PARAMS = {body};\n")
Path("js/intradayProbShadowParams.js").write_text(js)
print(ver[:16], json.dumps(out["delta"]), json.dumps(out["fit_rows"]))
