#!/usr/bin/env node
// Trial ledger — Forecaster Portfolio Lesson 02 §05: "the record of every attempt is the data that
// allows a search to account for its own breadth." Regenerates MD files/TRIAL_LEDGER.md from the
// Evidence Book (js/deskEvidence.js, the house register of banked verdicts) and lists every
// pre-registration file that never got a banked verdict, so nothing tried silently drops out.
//
//   node scripts/build_trial_ledger.mjs
//
// Adding a test: bank its verdict in js/deskEvidence.js (the existing pipeline), then re-run this.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { DESK_EVIDENCE } from '../js/deskEvidence.js';

const ROOTS = ['forge', 'MD files', 'oi_research_book'];
const OUT = 'MD files/TRIAL_LEDGER.md';

const E = [...DESK_EVIDENCE].sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.id.localeCompare(b.id)));
const count = v => E.filter(e => e.verdict === v).length;
const tested = E.filter(e => e.verdict !== 'context');           // context = base rates / descriptions, not tests
const passes = count('validated'), fails = count('null') + count('underpowered');
const N = tested.length;
// Lesson 02 §05 arithmetic. If NONE of the claims were real, a 5%-size test would still pass about
// 5% of them by chance. Against the observed passes that bounds how many could be luck.
const chance = Math.round(0.05 * N * 10) / 10;

const docsInLedger = new Set(E.map(e => String(e.doc ?? '').split('#')[0].trim()).filter(Boolean));
const prereg = [];
for (const r of ROOTS) {
  if (!existsSync(r)) continue;
  for (const f of readdirSync(r)) if (/PREREG.*\.md$/i.test(f)) prereg.push(join(r, f).replace(/\\/g, '/'));
}
// A test is banked when any ledger write-up shares its name, whichever file the entry cites
// (some cite the PREREG, others the RESULTS file: GEX_RANGE_BROWNIAN_PREREG vs _RESULTS).
const stem = p => p.split('/').pop().replace(/\.md$/i, '').replace(/_(PREREG|RESULTS?)$/i, '').toUpperCase();
const stems = new Set([...docsInLedger].map(stem));
const unbanked = prereg.filter(p => !/PREREG_TEMPLATE/i.test(p) && !docsInLedger.has(p) && !stems.has(stem(p))).sort();

const firstLine = p => {
  const t = readFileSync(p, 'utf8').split(/\r?\n/).find(l => /^#\s/.test(l));
  return t ? t.replace(/^#\s*/, '').slice(0, 110) : '';
};

const md = [
  '# Trial ledger',
  '',
  '*Generated by `node scripts/build_trial_ledger.mjs` from the Evidence Book (`js/deskEvidence.js`). Do not hand-edit:',
  'bank a verdict in the Evidence Book, then regenerate. Forecaster Portfolio Lesson 02 §05: a programme that records only',
  'its successes cannot correct for how hard it searched.*',
  '',
  `Generated ${new Date().toISOString().slice(0, 10)}.`,
  '',
  '## The count',
  '',
  '| | n |',
  '|---|---|',
  `| claims tested (validated + null + underpowered) | **${N}** |`,
  `| validated | ${passes} |`,
  `| null | ${count('null')} |`,
  `| underpowered | ${count('underpowered')} |`,
  `| context (base rates, descriptions: not counted as tests) | ${count('context')} |`,
  `| pre-registrations with no banked verdict (below) | ${unbanked.length} |`,
  '',
  `**What the count says (Lesson 02 §05).** If none of the ${N} claims were real, tests at the usual 5% size would still pass`,
  `about **${chance}** of them by luck. ${passes} passed, so most passes are unlikely to be luck alone, but`,
  `**roughly ${Math.round(chance)} of the ${passes} could be**. Which ones cannot be told from the backtest.`,
  'An independent second test is what separates them: a confirmation on untouched data (as US-EXTRAS-CONFIRM did) or the',
  'forward record (the nightly forecast scorecard). Until then, treat a single-test pass as probable, not proven.',
  '',
  '## Every banked test, oldest first',
  '',
  '| date | id | domain | verdict | write-up |',
  '|---|---|---|---|---|',
  ...E.map(e => `| ${e.date} | ${e.id} | ${e.domain} | ${e.verdict} | ${e.doc ?? ''} |`),
  '',
  '## Pre-registered, but no banked verdict',
  '',
  unbanked.length
    ? 'These were designed as tests but never reached the Evidence Book. Each is either still to run, or ran and was not banked (the second is the failure Lesson 02 warns about: a search that forgets its misses looks better than it is). Bank or close each one.'
    : 'None: every pre-registration has a banked verdict.',
  '',
  ...unbanked.map(p => `- \`${p}\`: ${firstLine(p)}`),
  '',
];
writeFileSync(OUT, md.join('\n'), 'utf8');
console.log(`wrote ${OUT}: ${N} tested (${passes} validated), ${count('context')} context, ${unbanked.length} pre-registrations unbanked`);
