// Compile the Event Response Book (backfill/event_response_book.json, built by
// scripts/build_event_response_book.mjs) into the small lookup the watch and
// today.html read: country|category -> instrument -> { spikeR0, moveMultiple, n }.
//
//   node scripts/build_event_impact_map.mjs        -> writes js/eventImpactMap.js
//
// One family per country|category: the one the market reacts to MOST (highest
// median 30-minute spike across its instruments, at least 40 events) -- the
// calendar names a release by vendor label and the page classifies it by
// category, so the lookup has to be by category, and "most events" picked PPI
// over CPI and the unemployment rate over payrolls. Reaction size is the right
// tie-breaker: it is what the chip is about. Only instruments with n >= 20 are kept, and
// only rows where the 30-minute spike clears 1.5x an ordinary half-hour -- the
// book's own finding is that most releases move nothing, and a chip that says
// "0.9x" is noise dressed as information.
import fs from 'fs';
const book = JSON.parse(fs.readFileSync('backfill/event_response_book.json', 'utf8'));
const CAT = { rates: 'rate decision', labor: 'employment', inflation: 'cpi', growth: 'gdp', 'business-activity': 'pmi', retail: 'retail sales' };
const best = {};
for (const [fk, meta] of Object.entries(book.families)) {
  const cat = CAT[meta.category]; if (!cat) continue;
  const key = `${meta.country}|${cat}`;
  const rows = book.book[fk]?.instruments ?? {};
  const inst = {};
  for (const [sym, r] of Object.entries(rows)) if (r.n >= 20 && Number.isFinite(r.spikeR0) && r.spikeR0 >= 1.5) inst[sym.toUpperCase()] = { spike: +r.spikeR0.toFixed(2), next: r.moveMultiple != null ? +r.moveMultiple.toFixed(2) : null, n: r.n, upPct: Array.isArray(r.r1) ? +r.r1[2].toFixed(0) : null };
  if (!Object.keys(inst).length || meta.events < 40) continue;
  const spikes = Object.values(inst).map(r => r.spike).sort((a, b) => a - b); const medSpike = spikes[Math.floor(spikes.length / 2)];
  if (!best[key] || medSpike > best[key].medSpike) best[key] = { family: fk, label: meta.label, events: meta.events, medSpike, instruments: inst };
}
// FOMC statement (keyed 'fomc') sits outside the country|category scheme; fold it into US|rate decision if larger.
const out = `// GENERATED by scripts/build_event_impact_map.mjs from backfill/event_response_book.json
// (Event Response Book, ${book.builtAt}). Do not edit by hand.
//
// country|category -> instrument -> { spike: 30-min |move| ÷ ordinary half-hour,
// next: next-day |move| ÷ ordinary day, n, upPct: next-day up-rate (a coin flip
// everywhere -- shown so no one mistakes the size map for a direction) }.
// Measurement only: what each release has done to each instrument, in size.
export const EVENT_IMPACT_MAP = ${JSON.stringify(best, null, 1)};

/** Lookup by calendar country code (US, GB, EU, JP, AU, CA, NZ, CH) and family. */
export function eventImpact(country, family) {
  return EVENT_IMPACT_MAP[\`\${country}|\${family}\`] ?? null;
}
`;
fs.writeFileSync('js/eventImpactMap.js', out);
console.log(`wrote js/eventImpactMap.js: ${Object.keys(best).length} country|category rows`);
for (const [k, v] of Object.entries(best)) console.log(`  ${k.padEnd(22)} ${v.label.padEnd(44)} ${Object.keys(v.instruments).length} instruments  median spike ${v.medSpike}x  (${v.events} events)`);
